### ISSUE TITLE
[AMI 0.19] Scylla crashes when trying to run nodetool rebuild (coredumps and stack traces available)

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#1038]
When running the cluster test suite on the 0.19 AMIs, we found a problem running the CorruptThenRebuildMonkey (more details on what the nemesis does later).

Cassandra-stress starts around 20:09:

    20:09:30 remote           L0773 DEBUG| Remote [centos@54.210.168.95]: Running 'cassandra-stress write cl=QUORUM duration=1440m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=1000 -node 172.30.0.240'

The first strange messages I find happen around 20:14:

    20:14:32 remote           L0182 DEBUG| [107.23.17.60] [stdout] Mar 11 20:14:33 ip-172-30-0-238 scylla[2722]: WARNING: exceptional future ignored of type 'std::system_error': Error system:17 (File exists)
    ...
    20:14:33 remote           L0182 DEBUG| [107.23.17.60] [stdout] Mar 11 20:14:33 ip-172-30-0-238 scylla[2722]:  [shard 1] storage_proxy - MUTATION verb handler: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID 30638430-e7c5-11e5-8ba0-000000000000)

The nemesis executes successfully 15 times:

    20:21:35 nemesis          L0218 DEBUG| sdcm.nemesis.CorruptThenRebuildMonkey: <function disrupt at 0x7fe16f408c08> duration -> 424 s
    ...
    23:09:14 nemesis          L0218 DEBUG| sdcm.nemesis.CorruptThenRebuildMonkey: <function disrupt at 0x7fe16f408c08> duration -> 421 s

The next nemesis execution will never finish, because the DB services won't come back up on the disrupted node

    23:16:17 wait             L0044 DEBUG| Node corrupt_then_rebuild_monkey-scylla-db-node-2dc3809d-3 [52.91.195.205 | 172.30.0.237] (seed: False): Waiting for DB services to be up (60.3229951859 s)
    ...
    20:12:01 wait             L0044 DEBUG| Node corrupt_then_rebuild_monkey-scylla-db-node-2dc3809d-3 [52.91.195.205 | 172.30.0.237] (seed: False): Waiting for DB services to be up (75403.6390181 s)

Looking in the log, I could pinpoint the reason that the service never started to this log snippet:

    23:14:30 remote           L0182 DEBUG| [52.91.195.205] [stdout] Mar 11 23:14:28 ip-172-30-0-237 scylla[4620]:  [shard 1] storage_proxy - MUTATION verb handler: seastar::gate_closed_exception (gate closed)
    ...
    23:15:17 remote           L0182 DEBUG| [52.91.195.205] [stdout] Mar 11 23:15:18 ip-172-30-0-237 scylla[4708]:  [shard 1] database - Populating Keyspace system
    23:15:17 remote           L0182 DEBUG| [52.91.195.205] [stdout] Mar 11 23:15:18 ip-172-30-0-237 scylla[4708]:  [shard 1] database - Keyspace /var/lib/scylla/data/system: Reading CF size_estimates
    23:15:17 remote           L0182 DEBUG| [52.91.195.205] [stdout] Mar 11 23:15:18 ip-172-30-0-237 scylla[4708]:  [shard 1] database - Keyspace /var/lib/scylla/data/system: Reading CF compaction_history
    23:15:17 remote           L0182 DEBUG| [52.91.195.205] [stdout] Mar 11 23:15:18 ip-172-30-0-237 scylla[4708]:  [shard 1] database - Keyspace /var/lib/scylla/data/system: Reading CF compactions_in_progress
    23:15:17 remote           L0182 DEBUG| [52.91.195.205] [stdout] Mar 11 23:15:18 ip-172-30-0-237 scylla[4708]:  [shard 1] database - Keyspace /var/lib/scylla/data/system: Reading CF range_xfers
    23:15:17 remote           L0182 DEBUG| [52.91.195.205] [stdout] Mar 11 23:15:18 ip-172-30-0-237 scylla[4708]:  [shard 1] database - Keyspace /var/lib/scylla/data/system: Reading CF sstable_activity
    23:15:17 remote           L0182 DEBUG| [52.91.195.205] [stdout] Mar 11 23:15:18 ip-172-30-0-237 scylla[4708]:  [shard 1] database - Keyspace /var/lib/scylla/data/system: Reading CF peers
    23:15:17 remote           L0182 DEBUG| [52.91.195.205] [stdout] Mar 11 23:15:18 ip-172-30-0-237 scylla[4708]:  [shard 1] database - Keyspace /var/lib/scylla/data/system: Reading CF schema_triggers
    23:15:17 remote           L0182 DEBUG| [52.91.195.205] [stdout] Mar 11 23:15:18 ip-172-30-0-237 scylla[4708]:  [shard 1] database - Keyspace /var/lib/scylla/data/system: Reading CF schema_columns
    23:15:17 remote           L0182 DEBUG| [52.91.195.205] [stdout] Mar 11 23:15:18 ip-172-30-0-237 scylla[4708]:  [shard 1] database - Keyspace /var/lib/scylla/data/system: Reading CF schema_columnfamilies
    23:15:17 remote           L0182 DEBUG| [52.91.195.205] [stdout] Mar 11 23:15:18 ip-172-30-0-237 scylla[4708]:  [shard 1] database - Keyspace /var/lib/scylla/data/system: Reading CF schema_keyspaces
    23:15:17 remote           L0182 DEBUG| [52.91.195.205] [stdout] Mar 11 23:15:18 ip-172-30-0-237 scylla[4708]: WARNING: exceptional future ignored of type 'sstables::malformed_sstable_exception': Invalid State encountered. Temporary TOC file found after TOC file was processed
    23:15:17 remote           L0182 DEBUG| [52.91.195.205] [stdout] Mar 11 23:15:18 ip-172-30-0-237 scylla[4708]: Exiting on unhandled exception of type 'sstables::malformed_sstable_exception': Invalid State encountered. Temporary TOC file found after TOC file was processed

Way before that, we also had a couple of core dumps. I couldn't find a causal relationship between events that might have triggered those, but at least we have stack traces and core dumps:

               PID: 3260 (scylla)
               UID: 994 (scylla)
               GID: 1001 (scylla)
            Signal: 6 (ABRT)
         Timestamp: Fri 2016-03-11 20:26:38 UTC (10min ago)
      Command Line: /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --num-io-queues 2 --max-io-requests 128
        Executable: /usr/bin/scylla
     Control Group: /system.slice/scylla-server.service
              Unit: scylla-server.service
             Slice: system.slice
           Boot ID: 1e3cdd7656054b068d35d2f2ee0bbc5e
        Machine ID: 8ea3e6ea03b64d018847fcdf669935d4
          Hostname: ip-172-30-0-243
          Coredump: /var/lib/systemd/coredump/core.scylla.994.1e3cdd7656054b068d35d2f2ee0bbc5e.3260.1457727998000000.xz
           Message: Process 3260 (scylla) of user 994 dumped core.
                    
                    Stack trace of thread 3260:
                    #0  0x00007fb2182aa5f7 raise (libc.so.6)
                    #1  0x00007fb2182abce8 abort (libc.so.6)
                    #2  0x00007fb2182a3566 __assert_fail_base (libc.so.6)
                    #3  0x00007fb2182a3612 __assert_fail (libc.so.6)
                    #4  0x0000000000c04198 execute_cql<char const* const&, basic_sstring<char, unsigned int, 15u>, utils::UUID&> (scylla)
                    #5  0x000000000078734b operator() (scylla)
                    #6  0x000000000078f8fc operator()<future_state<> > (scylla)
                    #7  0x00000000004ca71d _ZN7reactor9run_tasksER15circular_bufferISt10unique_ptrI4taskSt14default_deleteIS2_EESaIS5_EE (scylla)
                    #8  0x00000000004f574b _ZN7reactor3runEv (scylla)
                    #9  0x000000000056c430 _ZN12app_template14run_deprecatedEiPPcOSt8functionIFvvEE (scylla)
                    #10 0x00000000004708d8 main (scylla)
                    #11 0x00007fb218296b15 __libc_start_main (libc.so.6)
                    #12 0x00000000004c74f5 _start (scylla)
                    
                    Stack trace of thread 3265:
                    #0  0x00007fb21864422d read (libpthread.so.0)
                    #1  0x00000000004cae65 _ZN11thread_pool4workEv (scylla)
                    #2  0x00000000005452ce _ZNKSt8functionIFvvEEclEv (scylla)
                    #3  0x00007fb21863ddc5 start_thread (libpthread.so.0)
                    #4  0x00007fb21836b21d __clone (libc.so.6)
                    
                    Stack trace of thread 3262:
                    #0  0x00007fb21836b7f3 epoll_wait (libc.so.6)
                    #1  0x00000000006c76b4 eal_intr_thread_main (scylla)
                    #2  0x00007fb21863ddc5 start_thread (libpthread.so.0)
                    #3  0x00007fb21836b21d __clone (libc.so.6)
                    
                    Stack trace of thread 3264:
                    #0  0x00007fb21864422d read (libpthread.so.0)
                    #1  0x00000000004cae65 _ZN11thread_pool4workEv (scylla)
                    #2  0x00000000005452ce _ZNKSt8functionIFvvEEclEv (scylla)
                    #3  0x00007fb21863ddc5 start_thread (libpthread.so.0)
                    #4  0x00007fb21836b21d __clone (libc.so.6)
                    
                    Stack trace of thread 3263:
                    #0  0x00007fb21c074697 io_submit (libaio.so.1)
                    #1  0x00000000004c9e02 _ZN7reactor17flush_pending_aioEv (scylla)
                    #2  0x00000000004f5779 _ZN7reactor9poll_onceEv (scylla)
                    #3  0x00000000005162f9 _ZZN3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv.constprop.2877 (scylla)
                    #4  0x00000000004c7cce _ZNKSt8functionIFvvEEclEv (scylla)
                    #5  0x00000000006c3f55 eal_thread_loop (scylla)
                    #6  0x00007fb21863ddc5 start_thread (libpthread.so.0)
                    #7  0x00007fb21836b21d __clone (libc.so.6)

To download it, you may use `curl --user-agent [user-agent] scylladb-users-upload.s3.amazonaws.com/core.scylla.994.1e3cdd7656054b068d35d2f2ee0bbc5e.3260.1457727998000000/core.scylla.994.1e3cdd7656054b068d35d2f2ee0bbc5e.3260.1457727998000000.xz > core.scylla.994.1e3cdd7656054b068d35d2f2ee0bbc5e.3260.1457727998000000.xz`

               PID: 32361 (scylla)
               UID: 994 (scylla)
               GID: 1001 (scylla)
            Signal: 6 (ABRT)
         Timestamp: Fri 2016-03-11 21:38:39 UTC (8min ago)
      Command Line: /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --num-io-queues 2 --max-io-requests 128
        Executable: /usr/bin/scylla
     Control Group: /system.slice/scylla-server.service
              Unit: scylla-server.service
             Slice: system.slice
           Boot ID: 0acac5c4636d4a23af97a69277fb1628
        Machine ID: 8ea3e6ea03b64d018847fcdf669935d4
          Hostname: ip-172-30-0-237
          Coredump: /var/lib/systemd/coredump/core.scylla.994.0acac5c4636d4a23af97a69277fb1628.32361.1457732319000000.xz
           Message: Process 32361 (scylla) of user 994 dumped core.
                    
                    Stack trace of thread 32361:
                    #0  0x00007f87cf7db5f7 raise (libc.so.6)
                    #1  0x00007f87cf7dcce8 abort (libc.so.6)
                    #2  0x00007f87cf7d4566 __assert_fail_base (libc.so.6)
                    #3  0x00007f87cf7d4612 __assert_fail (libc.so.6)
                    #4  0x0000000000c04198 execute_cql<char const* const&, basic_sstring<char, unsigned int, 15u>, utils::UUID&> (scylla)
                    #5  0x000000000078734b operator() (scylla)
                    #6  0x000000000078f8fc operator()<future_state<> > (scylla)
                    #7  0x00000000004ca71d _ZN7reactor9run_tasksER15circular_bufferISt10unique_ptrI4taskSt14default_deleteIS2_EESaIS5_EE (scylla)
                    #8  0x00000000004f574b _ZN7reactor3runEv (scylla)
                    #9  0x000000000056c430 _ZN12app_template14run_deprecatedEiPPcOSt8functionIFvvEE (scylla)
                    #10 0x00000000004708d8 main (scylla)
                    #11 0x00007f87cf7c7b15 __libc_start_main (libc.so.6)
                    #12 0x00000000004c74f5 _start (scylla)
                    
                    Stack trace of thread 32364:
                    #0  0x00007f87cf89c7f3 epoll_wait (libc.so.6)
                    #1  0x00000000006c76b4 eal_intr_thread_main (scylla)
                    #2  0x00007f87cfb6edc5 start_thread (libpthread.so.0)
                    #3  0x00007f87cf89c21d __clone (libc.so.6)
                    
                    Stack trace of thread 32367:
                    #0  0x00007f87cfb7522d read (libpthread.so.0)
                    #1  0x00000000004cae65 _ZN11thread_pool4workEv (scylla)
                    #2  0x00000000005452ce _ZNKSt8functionIFvvEEclEv (scylla)
                    #3  0x00007f87cfb6edc5 start_thread (libpthread.so.0)
                    #4  0x00007f87cf89c21d __clone (libc.so.6)
                    
                    Stack trace of thread 32365:
                    #0  0x00007ffd9e30d7c2 __vdso_clock_gettime (linux-vdso.so.1)
                    #1  0x00007f87cf8afe6d __clock_gettime (libc.so.6)
                    #2  0x00000000014540f1 _ZNSt6chrono3_V212steady_clock3nowEv (scylla)
                    #3  0x00000000005086cb queue_request<posix_file_impl::read_dma(uint64_t, void*, size_t, const io_priority_class&)::<lambda(iocb&)> > (scylla)
                    #4  0x0000000000540c29 _ZN4file8dma_readIcEE6futureIJmEEmPT_mRK17io_priority_class (scylla)
                    #5  0x0000000000541aa7 _ZN21file_data_source_impl17issue_read_aheadsEj (scylla)
                    #6  0x0000000000542175 _ZN21file_data_source_impl3getEv (scylla)
                    #7  0x0000000000910f6a _ZN11data_source3getEv (scylla)
                    #8  0x00000000008d816c _ZN8sstables20random_access_reader12read_exactlyEm (scylla)
                    #9  0x00000000008d95e9 operator() (scylla)
                    #10 0x00000000008d9cec operator()<future_state<> > (scylla)
                    #11 0x00000000004ca71d _ZN7reactor9run_tasksER15circular_bufferISt10unique_ptrI4taskSt14default_deleteIS2_EESaIS5_EE (scylla)
                    #12 0x00000000004f574b _ZN7reactor3runEv (scylla)
                    #13 0x00000000005162f9 _ZZN3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv.constprop.2877 (scylla)
                    #14 0x00000000004c7cce _ZNKSt8functionIFvvEEclEv (scylla)
                    #15 0x00000000006c3f55 eal_thread_loop (scylla)
                    #16 0x00007f87cfb6edc5 start_thread (libpthread.so.0)
                    #17 0x00007f87cf89c21d __clone (libc.so.6)
                    
                    Stack trace of thread 32366:
                    #0  0x00007f87cfb7522d read (libpthread.so.0)
                    #1  0x00000000004cae65 _ZN11thread_pool4workEv (scylla)
                    #2  0x00000000005452ce _ZNKSt8functionIFvvEEclEv (scylla)
                    #3  0x00007f87cfb6edc5 start_thread (libpthread.so.0)
                    #4  0x00007f87cf89c21d __clone (libc.so.6)

To download it, you may use `curl --user-agent [user-agent] scylladb-users-upload.s3.amazonaws.com/core.scylla.994.0acac5c4636d4a23af97a69277fb1628.32361.1457732319000000/core.scylla.994.0acac5c4636d4a23af97a69277fb1628.32361.1457732319000000.xz > core.scylla.994.0acac5c4636d4a23af97a69277fb1628.32361.1457732319000000.xz`

Corrupt then rebuild monkey
===========================

What the nemesis does
---------------------

Destroy user data by running the script

    #!/bin/bash

    DELETE_COUNT=5

    ls /var/lib/scylla|sort -R |tail -$DELETE_COUNT |while read file; do
        rm -rf $file
    done

in one of the nodes

Run

    sudo pkill -9 scylla

On that same node.

Wait until DB services are down (Port 9042 not occupied)

Due to a scylla bug, we are restarting the scylla service in the test itself

    sudo systemctl restart scylla-server.service

Wait until DB services are up (Port 9042 occupied)

Run the following nodetool command in all cluster nodes:

    nodetool -h localhost rebuild

**Comment by lmr** [comment]
I forgot to mention I left the clusters up and running just in case someone wants access to it. I won't be keeping them indefinitely up, though.

**Comment by penberg** [comment]
@glommer @raphaelsc Is this already fixed in ``master`` by one of your sstable changes?

**Comment by raphaelsc** [comment]
As far as I can tell, we shouldn't be facing that problem anymore. For the record, that problem refers to "Mar 11 23:15:18 ip-172-30-0-237 scylla[4708]: Exiting on unhandled exception of type 'sstables::malformed_sstable_exception': Invalid State encountered. Temporary TOC file found after TOC file was processed". @glommer?

**Comment by glommer** [comment]
@penberg That is very likely the same issue as #1014 , or at least partially, which is very good news.
However, I would not dare to say this is fixed until all the verbs get their initialization delayed.

I see there is a patch that moved some verbs' initialization to a later time. Did that patch move all verbs' initialization?

**Comment by penberg** [comment]
@glommer No, not all of them.

**Comment by glommer** [comment]
@penberg Our patches will prevent further corruption by not allowing a new table to overwrite existing ones. But if a verb arrives too early and we trigger a write, we'll still crash.

So is it fixed? Technically it depends on which verb is the early bird here, but in a broad level, no.

**Comment by lmr** [comment]
Scylla package versions:

    scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64
    scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
    scylla-boost-system-1.58.0-11.el7.centos.x86_64
    scylla-boost-test-1.58.0-11.el7.centos.x86_64
    scylla-boost-thread-1.58.0-11.el7.centos.x86_64
    scylla-env-1.0-1.el7.centos.noarch
    scylla-gdb-7.10.1-30.el7.centos.x86_64
    scylla-jmx-0.19-20160310.ac51e7f.el7.centos.noarch
    scylla-server-0.19-20160310.7c12687.el7.centos.x86_64
    scylla-server-debuginfo-0.19-20160310.7c12687.el7.centos.x86_64
    scylla-tools-0.19-20160310.0bd0b18.el7.centos.noarch

**Comment by gleb-cloudius** [comment]
update_schema_version() is called before std::unique_ptr<query_context> qctx is initialized

**Comment by slivne** [comment]
So is this fixed now by boot order update ?

**Comment by gleb-cloudius** [comment]
It may be. From the core it is not clear who called update_schema_version() to early. Since in the log we have complains from mutation verb it is reasonable to assume it was responsible in which case problem should be fixed already, but this is just assumptions.

**Comment by gleb-cloudius** [comment]
Do we have a full log for that?

**Comment by slivne** [comment]
@lmr ?

**Comment by lmr** [comment]
@gleb-cloudius and @slivne sure, there is a full log for the test. It's just humongous and therefore may be hard to read. I can compress it and upload it somewhere.

**Comment by gleb-cloudius** [comment]
On Tue, Mar 15, 2016 at 07:26:08AM -0700, Lucas Meneghel Rodrigues wrote:
> @gleb-cloudius and @slivne sure, there is a full log for the test. It's just humongous and therefore may be hard to read. I can compress it and upload it somewhere. 
> 
Have you?

--
			Gleb.

**Comment by slivne** [comment]
you can use the following ami of head to retest this ami-e3787a89

**Comment by lmr** [comment]
The problem seems to be fixed with the latest 1.0-rc1 ami-c25e51a8, I'm closing this issue.
