### ISSUE TITLE
Error message to user with unnecessary technical details

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3108]
*Installation details*
Scylla version (or git commit hash): master

In case some problem during query run, error message has unnecessary technical details, like _org.apache.cassandra.db.marshal.IntegerType_ or _system.max_.
I suggest to change it to more user friendly message

Example of the error message:
InvalidRequest: Error from server: code=2200 [Invalid query] message="Ambiguous call to function max (can be matched by following signatures: system.max : (org.apache.cassandra.db.marshal.IntegerType) -> org.apache.cassandra.db.marshal.IntegerType, system.max : (org.apache.cassandra.db.marshal.LongType) -> org.apache.cassandra.db.marshal.LongType): use type casts to disambiguate"

**Comment by slivne** [comment]
@juliayakovlev - we try to align the error messages with cassandra so that clients will be able to parse them in the same manner.

Are Scylla's and Cassandra error messages the same ?

**Comment by juliayakovlev** [comment]
@slivne 
Example of Cassandra message in similar situation:
InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid call to function avg, none of its type signatures match (known type signatures: system.avg : (float) -> float, system.avg : (tinyint) -> tinyint, system.avg : (bigint) -> bigint, system.avg : (int) -> int, system.avg : (counter) -> counter, system.avg : (double) -> double, system.avg : (decimal) -> decimal, system.avg : (smallint) -> smallint, system.avg : (varint) -> varint)"

As you can see, they do not print packages' names like "org.apache.cassandra.db.marshal.IntegerType". They print "int" instead. It seems more user friendly. 
They still print "system.avg". On my opinion, it also should be change to "avg"

**Comment by hagrid-the-developer** [comment]
During the code review @avikivity claimed that removing system. from function name can lead to ambiguity. So since it isn't as annoying as prefix in data-types and since C* prints it, we can probably leave with it. Otherwise, prefixes for types should be fixed.

**Comment by hagrid-the-developer** [comment]
I think we can close this issue.

**Comment by nyh** [comment]
I still see those long type names like `org.apache.cassandra.db.marshal.LongType` in various messages. This is:
1. Ugly
2. Advertises Apache Cassandra ;-)
3. And confusing for users because the name of this type in CQL isn't "LongType", it's "bigint".

We should use the CQL type names - like bigint - in messages.
