### ISSUE TITLE
Data amount in the MV less then expected after cluster restart with resharding

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3452]
Dtest  interrupt_build_process_with_resharding_half_to_max_test failed with error:

**Failure**
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/home/juliay/scylla_repo/scylla-dtest/materialized_views_test.py", line 1917, in interrupt_build_process_with_resharding_half_to_max_test
    self._do_resharding_test(str(cpu_count() / 2), str(cpu_count() - 1))
  File "/home/juliay/scylla_repo/scylla-dtest/materialized_views_test.py", line 1983, in _do_resharding_test
    assert_row_count(session, 't_by_v2', rows, consistency_level=ConsistencyLevel.ALL);
  File "/home/juliay/scylla_repo/scylla-dtest/assertions.py", line 76, in assert_row_count
    expected, table_name, count)
AssertionError: Expected a row count of 200000 in table 't_by_v2', but got 199961

**Test scenario:**
Inserting initial data; smp = 4
Create a couple of MVs
Ensure view building started.
Stop the cluster. Interrupt the MV build process.
Ensure view building didn't finish.
Restart the cluster with shards 7
Starting node node1
Starting node node2
Starting node node3
Wait and ensure the MV build resumed.
Waiting for view ks.t_by_v to finish building...
Waiting for view ks.t_by_v2 to finish building...
Verify all data
SELECT count(*) FROM t_by_v
SELECT count(*) FROM t_by_v2

Scylla last commit: 
0c54c6e16fc4cb3b3dcc3a3b954a953c1e18d949

**Comment by duarten** [comment]
Stopping the cluster forces the nodes to go down and doesn't do an orderly shutdown, so one thing that could maybe explain this would be an un-flushed commit log.

I don't think there's a bug per se, but we should understand the behavior nonetheless. 

@juliayakovlev Also told me a similar error happens in the non-MV resharding tests, so it may be unrelated to MVs after all.

**Comment by slivne** [comment]
@juliayakovlev how do we stop the nodes - is that will kill -9 or a clean shutdown.

if its a clean shutdown then its a bug.

If its kill -9 we may be missing something - can you try clean shutdown and see if this happens.

**Comment by duarten** [comment]
I wrote those tests. It's not a clean shutdown. A clean shutdown takes too long, and the build process is not interrupted.

**Comment by slivne** [comment]
@duarten
 - unflushed commitlog for which table - the view_building tables or some other table ?
- shouldn't the create view assure that the view_building tables (the initial one data - before the building starts) would be persisted (flushed) before the create view is returned ?
- do we have any gurantee that the view_building table data has been flushed before building starts - I think we should at least have that

**Comment by duarten** [comment]
@slivne The commitlog for the view table. 

I don't understand what you mean about the other points. What is "create view is returned"? What's the `view_building` table? Do you mean the bookkeeping tables for the view building process? Why would they be flushed before the build started?

**Comment by tzach** [comment]
@slivne ping

**Comment by slivne** [comment]
@duarten 

The only explanation I have to why this can happen is if prior to the crash we flushed the commitlog/book keeping tables and did not flush commitlog/tables of views. 

Is this the scenario you assume we hit - or some other case ?

(If bookeeping has not been written (to commitlog or sstable) AFAIK the process will pickup and redo those parts.)

**Comment by duarten** [comment]
I think there might be a bug in the resharding code for view building. There were some failures of the resharding dtests that causes the view to not be built. It points to a problem with accounting in the view builder that might also explain this.

**Comment by slivne** [comment]
thanks

**Comment by duarten** [comment]
@slivne I won't likely have cycles to look into this.

**Comment by nyh** [comment]
Hi @juliayakovlev I'm trying to reproduce this bug, without success. I ran it with the "monster virtual environment" which Shlomi gave me, and ran it multiple times, but it succeeded every time. Did you see this bug once, many times, or what? Any other hints you can give me on how to reproduce it?

**Comment by juliayakovlev** [comment]
@nyh  as far as I remember this problem didn't happen every run (like all such kind of problem). 
It was no special configuration. just regular run 
This issue was opened at May, maybe it has been fixed already?

**Comment by duarten** [comment]
There was no fix to this.

There were recent reports of interrupt_build_process_with_resharding_XXX_test failing, no? In particular, failing by not being able to build the view. Quoting myself from end of August:

> Now, this said, I think there's a real bug with resharding. We shouldn't fail to build the view since we already wait for a long time. It could happen theoretically if the machine is very overloaded, but it's doubtful. You also said we fail during data validation, which means we already saw the view marked as built. In view building, we apply view updates synchronously (that is, eventually() wouldn't help), and only mark views as built after writing all of the view data, so this points to a real issue. Unfortunately, I couldn't repro this, but I shall try again.

**Comment by nyh** [comment]
@duarten you wrote:
"I wrote those tests. It's not a clean shutdown. A clean shutdown takes too long, and the build process is not interrupted."
But I look at the code and see:
```
self.cluster.stop()
```
But cluster.stop() defaults to:
```
    def stop(self, wait=True, gently=True):
```
so it seems we *do* a clean shutdown here... What am I missing?

**Comment by nyh** [comment]
A few more observations:

1. This bug still happening sporadically. For example, http://jenkins.cloudius-systems.com:8080/job/scylla-master-dtest/label=scylla-dtest,mode=release,smp=2/887/testReport/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_half_to_max_test/ from two weeks ago
2. This test is failing once every few runs - see http://jenkins.cloudius-systems.com:8080/job/scylla-master-dtest/label=scylla-dtest,mode=release,smp=2/887/testReport/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_half_to_max_test/history/ - but the failure is not always the one described in this bug (in other cases, reads become unresponsive, nodes do not boot up, and similar issues which seem unrelated).
3. It seems, also from the logs, that my previous comment was correct and we shut down the cluster cleanly in the middle of the build, so unflushed memtables or commitlogs are not a problem. It may be a genuine view-building bug.
4. The failing test interrupts a view build process in the middle, and restarts it with more shards, and it sometimes fails. We have a different test, interrupt_build_process_test, which is very similar except it has two views (hopefully irrelevant...) and resumes with the same number of shards. That test always succeeds - see http://jenkins.cloudius-systems.com:8080/job/scylla-master-dtest/label=scylla-dtest,mode=release,smp=2/887/testReport/materialized_views_test/TestMaterializedViews/interrupt_build_process_test/history/.

All of the above lead me to agree with Duarte's guess that this is a real bug in the **resharding** part of view building (or resharding in general?) and not in regular view building.

**Comment by duarten** [comment]
Huh, I was sure `cluster.stop()` has `gently=False`, but it's my fault for trusting default arguments.

**Comment by nyh** [comment]
Another thing I just realized about this test: It calls self.prepare() *without* an rf parameter. But this function defaults to rf=1, so that's what we have. So each node has a different subsection of rows, so if just one forgets to build some view rows, we won't have them during the final read.

**Comment by nyh** [comment]
I was able to reproduce this issue (unfortunately only once) and have a detailed log - with the pre-existing debug-level logs, and can see better how the build was interrupted and what reshard() in the view building code did. 

The test has two views - t_by_v and t_by_v2. By the time we stopped node 2, it has already finished building both of them. node 1, it has recently finished building t_by_v, and for t_by_v2, it only started, and only a few of the shards completed any build step - the rest didn't. So the reshard() algorithm in view.cc decides to start the build from scratch, and indeed we see after starting node 1 with more shards that it builds from scratch:
```
INFO  2018-10-17 10:42:00,050 [shard 0] view - Building view ks.t_by_v2, starting at token minimum token
```
When node 3 was killed , again t_by_v was finished building, but t_by_v2 made progress on all shards, and reshard() decided to restart the build here:
```
INFO  2018-10-17 10:42:30,355 [shard 0] view - Resuming to build view ks.t_by_v2 at -8590552082949118231
```
This makes sense - this was the last build step that shard 4 finished:
```
DEBUG 2018-10-17 10:40:56,636 [shard 4] view - Completed build step for base ks.t, at token -8590552082949118231; views={t
_by_v2}
```
So it appears that the view-building reshard(), and progress book-keeping, is working reasonably well.

I'm starting to suspect maybe hints and possibly their resharding or their shutdown order or something has something to do with this bug. The 3 nodes die at different times. Node 2 dies 30 seconds after the other two. In those 30 seconds, it has time to "complete" the view building, but a (relatively small) part lot of its work was not send to the other two nodes but rather written to hints. If we have a bug losing some hints for a completed view build, or on flushing them during shutdown, in replaying them on startup, or in resharding them on startup - we will not get all those view writes done, and some view rows will be missing.

I still need to understand what the logs tell me about what happens with the hints. I see log messages like this when node 2 (the one who should have saved hints) during the shutdown during the build:
```
DEBUG 2018-10-17 10:41:33,626 [shard 1] commitlog - Issuing sync for all segments (active)
DEBUG 2018-10-17 10:41:33,626 [shard 1] commitlog - Issuing sync for all segments (shutdown)
DEBUG 2018-10-17 10:41:33,626 [shard 1] commitlog - Segment HintsLog-1-18014398561560358.log is no longer active and will submitted for delete now
DEBUG 2018-10-17 10:41:33,626 [shard 1] commitlog - Deleting segment file /ssd/.dtest/dtest-setDGg/test/node2/data/view_pending_updates/1/127.0.0.1/HintsLog-1-18014398561560358.log
INFO  2018-10-17 10:41:33,626 [shard 1] hints_manager - Stopped
```
And during the startup I see the following messages:
```
WARN  2018-10-17 10:41:58,010 [shard 0] database - Skipping undefined keyspace: view_pending_updates
DEBUG 2018-10-17 10:42:21,830 [shard 7] commitlog - Deleting segment file /ssd/.dtest/dtest-setDGg/test/node2/data/view_pending_updates/7/127.0.0.1/HintsLog-1-126100789618711096.log
``` 
I hope this is not deleting the hints segment... I still need to understand what these messages mean.
Unfortunately the hits resharding operation - `db::hints::manager::rebalance(cfg->data_file_directories()[0] + "/view_pending_updates").get();` - does not have any debug-level log messages, so I still haven't seen evidence if it worked properly.

P.S. Note that the fact it takes time to replay the hints during startup and we don't wait for it *cannot* be the problem, because this test is in an eventually() loop, retried for several minutes. Even the last of those retries sees that rows are missing.

**Comment by duarten** [comment]
That message (`Skipping undefined keyspace: view_pending_updates`) does not sound good. We should skip this directory when populating the database (/cc @psarna).

Deleting the segment file can be because the hints were replayed. Too bad you didn't have hints trace logging enabled (the logger name is `hints_manager`).

I think your hypothesis is very reasonable. Hints do resharding, and a node may try to start sending hints to another node that is still booting, when we restart the cluster. It's a tough scenario.

**Comment by nyh** [comment]
I'm enabled all the tracing in hints_manager, but unfortunately cannot reproduce this bug any more... I'm still trying.
@duarten about the last line in your previous comment - why would a node start to send hints to another node before it is available? Don't we start sending hints only when the target node becomes available?

**Comment by duarten** [comment]
@nyh Quiet possibly, yes. I don't know if we send and ask questions later, or if we check the node status. Or if we load an old node status from the system tables.

**Comment by psarna** [comment]
On 10/17/18 8:48 PM, Duarte Nunes wrote:
>
> That message (|Skipping undefined keyspace: view_pending_updates|) 
> does not sound good. We should skip this directory when populating the 
> database (/cc @psarna <https://github.com/psarna>).
>
Ouch. Back then we decided to put view_pending updates in data 
directory, so it uses the same mountpoint as data, but right now nothing 
prevents users from creating view_pending_updates keyspace... simplest 
way - mark this name unavailable, it won't likely be used by anyone ever 
anyway. And I wonder if we should prefix it with system_, so nobody 
would be tempted to touch it (it's not a system table per se, though).
