### ISSUE TITLE
cqlsh provided with Scylla and COPY command - incorrect line parsing

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylla#3896]
cqlsh build from the current master branch is trying to interpret the parameters in a COPY command incorrectly:

```
[centos@ip-10-0-0-137 scylla-tools-java]$ cqlsh -k test -e "COPY datapoints_history_test FROM 'tabtest.csv' with DELIMITER='\t';" --debug
Using CQL driver: <module 'cassandra' from '/usr/share/scylla/cassandra/lib/cassandra-driver-internal-only-3.11.0-bb96859b.zip/cassandra-driver-3.11.0-bb96859b/cassandra/__init__.py'>
Using connect timeout: 5 seconds
Using 'utf-8' encoding
Using ssl: False
Detected 2 core(s)
Using 1 child processes

Starting copy of test.datapoints_history_test with columns [tid, node_id, channel, date, ts, v].
Closing parent cluster sockets
Closing parent cluster sockets
<stdin>:1:Failed to import 0 rows: IOError - Can't open "tabtest.csv' with DELIMITER='\\t" for reading: no matching file found,  given up after 1 attempts
Closing queues...
Processed: 0 rows; Rate:       0 rows/s; Avg. rate:       0 rows/s
0 rows imported from 0 files in 0.111 seconds (0 skipped).
```

For some reason, it looks like " `tabtest.csv' with DELIMITER='\\t` " is seen as the filename. 

* The same behaviour is observed with cqlsh 5.0.1 installed along with Scylla 2.2

With the current appache cqlsh from https://www-us.apache.org/dist/cassandra/3.11.3/apache-cassandra-3.11.3-bin.tar.gz everything works:

```
~/apache-cassandra-3.11.3/bin/cqlsh -k test -e "COPY datapoints_history_test FROM 'tabtest.csv' with DELIMITER = '\t';" --debug
Using CQL driver: <module 'cassandra' from '/home/centos/apache-cassandra-3.11.3/bin/../lib/cassandra-driver-internal-only-3.11.0-bb96859b.zip/cassandra-driver-3.11.0-bb96859b/cassandra/__init__.py'>
Using connect timeout: 5 seconds
Using 'utf-8' encoding
Using ssl: False
Detected 2 core(s)
Using 1 child processes
Renaming existing import_test_datapoints_history_test.err to import_test_datapoints_history_test.err.20181029_200835


Starting copy of test.datapoints_history_test with columns [tid, node_id, channel, date, ts, v].
Closing parent cluster sockets
Closing parent cluster sockets
Closing queues...s; Rate:      53 rows/s; Avg. rate:      53 rows/s
Processed: 14 rows; Rate:      27 rows/s; Avg. rate:      38 rows/s
14 rows imported from 1 files in 0.364 seconds (0 skipped).
```

**Comment by dyasny** [comment]
@glommer FYI

**Comment by tzach** [comment]
@dyasny I'm trying to reproduce
Can you please add the schema and the cvs file?
What version of Scylla are you using?

**Comment by dyasny** [comment]
Sample csv: 
```
7|10176734|part.a3|2017-08-21|2017-08-21 06:21:12|5.16
7|13932006|M1.12-34-v|2017-08-21|2017-08-21 09:21:15|29.6
7|13932006|M1.12-32-v|2017-08-21|2017-08-21 09:21:16|27.8
7|10138114|part.flow|2017-08-21|2017-08-21 06:21:18|4.32
7|10138114|part.pm1|2017-08-21|2017-08-21 06:21:18|1.54
7|13935421|M1.signal|2017-08-21|2017-08-21 09:21:15|41
7|10138114|part.pm2_5|2017-08-21|2017-08-21 06:21:18|2.35
7|13935421|M1.log-modbus|2017-08-21|2017-08-21 09:21:17|MODBUS: -info- Reading device number 1 ... MODBUS: -info- Starting loop for Scaled on 3003  ... MODBUS: Error in modbus loop: The bytestring is too short: 0, but minimum value is 2. Given: '' ... MODBUS: -info- Starting loop for test on 3002  ... MODBUS: -info- Starting loop for MV on 3002
7|10138114|part.pm10|2017-08-21|2017-08-21 06:21:18|4.18
7|10138114|part.vin|2017-08-21|2017-08-21 06:21:18|13.5
7|10138114|part.a3|2017-08-21|2017-08-21 06:21:18|5.23
7|13936386|poc.countdown|2017-08-21|2017-08-21 08:21:18|00:14:49
7|10177788|M1.2-16-v|2017-08-21|2017-08-21 08:21:20|0
7|13932001|M1.vin|2017-08-21|2017-08-21 09:21:19|23.99
```
I converted it to tab delim instead of pipe using sed (sed -i 's/|/\t/g' test.csv)
Schema: 
```
CREATE TABLE data.datapoints_history_test (
    tid int,
    node_id int,
    channel text,
    date text,
    ts timestamp,
    v blob,
    PRIMARY KEY ((tid, node_id, channel, date), ts)
) WITH CLUSTERING ORDER BY (ts ASC)
```

**Comment by dyasny** [comment]
I'll need to build an env for that, so not yet

**Comment by glommer** [comment]
as far as I remember, @dyasny , we did test with the new scylla tooling, that's the first thing we did.
problem was still there.

**Comment by dyasny** [comment]
@glommer yes, we tested with something from the master tree, and it was exactly the same stuff 2.2 and 2.3.1 has. I'm not sure this is what 3.0.rc1 actually shipped with

**Comment by slivne** [comment]
@dyasny 3.0 is shipped with tools based on cassandra 3.11 train - 2.3 was based on cassandra 3.0 ... so we have merged many fixes that have been done.

**Comment by dyasny** [comment]
This is in 3.0-rc2 in docker:

```[root@97d2f3b17668 /]# cqlsh -k data -e "COPY datapoints_history_test FROM 'test.csv' with DELIMITER = '\t';" --debug
Using CQL driver: <module 'cassandra' from '/usr/share/scylla/cassandra/lib/cassandra-driver-internal-only-3.11.0-bb96859b.zip/cassandra-driver-3.11.0-bb96859b/cassandra/__init__.py'>
Using connect timeout: 5 seconds
Using 'utf-8' encoding
Using ssl: False
Using options: '{}'
Detected 8 core(s)
Using 7 child processes

Starting copy of data.datapoints_history_test with columns [tid, node_id, channel, date, ts, v].
Closing parent cluster sockets
Closing parent cluster sockets
Closing parent cluster sockets
Closing parent cluster sockets
Closing parent cluster sockets
Closing parent cluster sockets
Closing parent cluster sockets
Closing parent cluster sockets
<stdin>:1:Failed to import 0 rows: IOError - Can't open "test.csv' with DELIMITER = '\\t" for reading: no matching file found,  given up after 1 attempts
Closing queues...
Closing queues...
Closing queues...
Closing queues...
Closing queues...
Closing queues...
Closing queues...
Processed: 0 rows; Rate:       0 rows/s; Avg. rate:       0 rows/s
0 rows imported from 0 files in 0.234 seconds (0 skipped).
```

Also tried various options of playing with the apostrophes, double chars etc - same result. 

```
# cqlsh --version
cqlsh 5.0.1

# scylla --version
3.0.rc2-0.20181212.6b011fbe0
```

**Comment by slivne** [comment]
lets start with verifying cassandra

**Comment by mlsmaycon** [comment]
It seems like there is an issue when using the option delimiter. For instance if I set a semi-colon, pipe or even a comma as delimiter I still receiving the same type of error, I've added all my test information in the link https://gist.github.com/mlsmaycon/46be46737187ec95c238087e2a063b37

**Comment by Kvark1205** [comment]
Have the same issue here. Also tried various options with the apostrophes as below but it still recognize it as filepath if I using custom delimiter: 

`Failed to import 0 rows: IOError - Can't open "/msgs.csv' WITH DELIMITER='\\t" for reading: no matching file found,  given up after 1 attempts`

Using docker container with scylladb/scylla:latest image
```
[root@d9d1fa937d09 /]# scylla --version
3.0.10-0.20190815.b3bfd8c08
[root@d9d1fa937d09 /]# cqlsh --version
cqlsh 5.0.1
```

**Comment by dyasny** [comment]
Another issue came up today:

Scylla 3.0.10

CQLsh shipped with Scylla:
```
COPY sales.tbl TO 'test.csv' WITH DELIMITER='|';

la -l
-rw-rw-r--. 1 centos centos    107032 Sep 16 14:57 test.csv' WITH DELIMITER=\'|\
```

cqlsh built from c* git:
```
Connected to test123 at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> COPY t1 TO STDOUT WITH DELIMITER = '|';
Not in any keyspace.
cqlsh> use test ;
cqlsh:test> COPY t1 TO STDOUT WITH DELIMITER = '|';
1|1
2|2
cqlsh:test> 
```
Copy to file works perfectly as well. 

Also tried with the latest version in pip, but that one is also broken in a different way


@slivne @glommer there is some impact we are seeing, maybe it's time to give this issue some love?

**Comment by vladzcloudius** [comment]
@eliransin ping

**Comment by ultrabug** [comment]
For what's it's worth, I'm also affected by this issue which prevents me from extracting data from scylla easily!...

Workaround is to use binary cqlsh from cassandra sources... :man_facepalming:

**Comment by dyasny** [comment]
@jul-stas ping - maybe you can provide some input here?

**Comment by vladzcloudius** [comment]
@eliransin Ping

**Comment by thorro** [comment]
Having the same issue, Scylla v3.2.1:

`copy mkn (<redacted>) from '/tmp/mkn2' with delimiter=';';
Using 3 child processes

Starting copy of ks1.mkn with columns [<redacted>].
Failed to import 0 rows: IOError - Can't open **"/tmp/mkn2' with delimiter=';"** for reading: no matching file found,  given up after 1 attempts`

**Comment by tarzanek** [comment]
fwiw checked our and their codebases for the problematic file and there is no difference
so the current hypothesis to test is the python version that we use and that cassandra uses, which seems to be the cause
(e.g. will scylla script run properly with the python version that cassandra uses?)

**Comment by dorlaor** [comment]
@tzach  @slivne I just got a report from a user who hit it again.
Need to figure out why there is an issue since @tarzanek claims the code
is the same as C*

**Comment by tomer-sandler** [comment]
@tzach @slivne that user Dor mentioned is a paying customer, and they wrote this 
```
ended up just downloading cassandra's cqlsh to use for an import instead
```

So something is different from C* , where it  actually worked.

**Comment by tzach** [comment]
@tarzanek did you validate the Python version theory?

**Comment by tarzanek** [comment]
hi, no, so the python version needs to be checked

**Comment by eliransin** [comment]
@tarzanek if you have time, can you try the problematic command with latest scylla oss or enterprise (not 2019.1 even though it should work there as well),
as far as I saw the libraries were merged from upstream so it should be working now. If you don't get to it I will eventually do it, I simply don't have bandwidth.
Thanks,

**Comment by tarzanek** [comment]
> 
> 
> @tarzanek if you have time, can you try the problematic command with latest scylla oss or enterprise (not 2019.1 even though it should work there as well),
> as far as I saw the libraries were merged from upstream so it should be working now. If you don't get to it I will eventually do it, I simply don't have bandwidth.
> Thanks,

doing it right now, since i have found a VM with lab upgraded it with 3.3 scylla and old files I used to test this, will update in few mins

**Comment by tarzanek** [comment]
so both used python 2.7
so this means that the diff is in the libraries that cqlsh.py uses
meaning cqlshlib must contain fixes for this

**Comment by tarzanek** [comment]
ok, got a fix, I tested:
```
$ git diff
diff --git a/pylib/cqlshlib/copyutil.py b/pylib/cqlshlib/copyutil.py
index 7f97b49..a4fb946 100644
--- a/pylib/cqlshlib/copyutil.py
+++ b/pylib/cqlshlib/copyutil.py
@@ -43,6 +43,8 @@ from select import select
 from uuid import UUID
 from util import profile_on, profile_off

+from six import ensure_str, ensure_text
+
 from cassandra import OperationTimedOut
 from cassandra.cluster import Cluster, DefaultConnection
 from cassandra.cqltypes import ReversedType, UserType
@@ -319,9 +321,9 @@ class CopyTask(object):
         opts = self.clean_options(self.maybe_read_config_file(opts, direction))

         dialect_options = dict()
-        dialect_options['quotechar'] = opts.pop('quote', '"')
-        dialect_options['escapechar'] = opts.pop('escape', '\\')
-        dialect_options['delimiter'] = opts.pop('delimiter', ',')
+        dialect_options['quotechar'] = ensure_str(opts.pop('quote', '"'))
+        dialect_options['escapechar'] = ensure_str(opts.pop('escape', '\\'))
+        dialect_options['delimiter'] = ensure_str(opts.pop('delimiter', ','))
         if dialect_options['quotechar'] == dialect_options['escapechar']:
             dialect_options['doublequote'] = True
             del dialect_options['escapechar']
```

**Comment by tarzanek** [comment]
above is a snippet taken from
https://github.com/apache/cassandra/commit/bf9a1d487b9ba469e8d740cf7d1cd419535a7e79
check copyutil diffs
so basically they fixed this during python 3 upgrade

**Comment by tarzanek** [comment]
well actually sorry for confusion
it seems above is not needed, master from https://github.com/scylladb/scylla-tools-java
just works - so something between 3.3 and master already has a fix it seems

**Comment by tarzanek** [comment]
this is weird, if I run locally from checkout
`./scylla-tools-java/bin/cqlsh -f copybug3896.cql`
it works
if I run from system
`/opt/scylladb/share/cassandra/bin/cqlsh -f copybug3896.cql`
it creates wrong file

diff between system and local master doesn't show the difference (or I am looking in wrong places, cqlsh.py , cqlshlib)
I'll checkout 3.3 branch and compare local run Vs system run

**Comment by tarzanek** [comment]
ok, not needed
so it seems fix is:
```
$ diff /opt/scylladb/share/cassandra/pylib/cqlshlib/cql3handling.py /opt/scylladb/share/cassandra/pylib/cqlshlib/cql3handling.py.orig
145a146,147
> <quotedStringLiteral> ::= /'([^']|')*'/ ;
> <pgStringLiteral> ::= /(\$\$).*(\$\$)/ ;
```

**Comment by tarzanek** [comment]
ok, double confirmed, so master has this fixed thanks to https://github.com/scylladb/scylla-tools-java/commit/e813778bd1d308dd9fd8b0ec6a6f646c92cecd0a

**Comment by tarzanek** [comment]
so https://github.com/scylladb/scylla-tools-java/issues/150 is a dup of this (or vice versa)

**Comment by eliransin** [comment]
First of all thanks for checking. I am 99% sure the fix is also in 2019.1.7 

> ok, double confirmed, so master has this fixed thanks to [scylladb/scylla-tools-java@e813778](https://github.com/scylladb/scylla-tools-java/commit/e813778bd1d308dd9fd8b0ec6a6f646c92cecd0a)

I will have a look what commit fixes it but if is prior to my change. The problem is also parsing but a different one and it is fixed by merging upstream (cassandra's) into scylla-tools-java by @elcallio 
If you have an easy reproducer maybe you can put it here so I can check starting from which 2019.1.x this fix is in.

**Comment by tarzanek** [comment]
reproducer is easy:
```
cat sample.cql
CREATE KEYSPACE mykeyspace WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1};

use mykeyspace;

CREATE TABLE users ( user_id int, fname text, lname text, PRIMARY KEY((user_id)));


insert into users(user_id, fname, lname) values (1, 'rick', 'sanchez');
insert into users(user_id, fname, lname) values (4, 'rust', 'cohle');

select * from users;
```
```
cqlsh -f sample.cql
```
And then repro:
```
cat copybug3896.cql
COPY mykeyspace.users TO 'test.csv' WITH DELIMITER='|';
```
```
cqlsh -f copybug3896.cql
```

**Comment by tarzanek** [comment]
2019.1.7 (upgraded from older version) reproduces for me
it has /usr/lib/python2.7/site-packages/cqlshlib/cql3handling.py with old contents still

**Comment by tarzanek** [comment]
so it seems https://github.com/scylladb/scylla-tools-java/commit/e813778bd1d308dd9fd8b0ec6a6f646c92cecd0a needs a backport to enterprise

**Comment by tarzanek** [comment]
after patching cql3handling on 2019.1.7 it works

**Comment by debashish-ghosh** [comment]
I observed the same issue in 2020.1.3.
cql3handling.py file has the bug still.

**Comment by debashish-ghosh** [comment]
I observed the same issue in 2020.1.3.
Had to manually patch https://github.com/scylladb/scylla-tools-java/commit/e813778bd1d308dd9fd8b0ec6a6f646c92cecd0a for a workaround.

**Comment by kostja** [comment]
Fixed, the issue is tracked in https://github.com/scylladb/scylla-tools-java/issues/150
