### ISSUE TITLE
Restarting a node which is at the old version during rolling upgrade fails

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#4458]
Scylla version (or git commit hash): Reproduced in 3.0.4
Cluster size: 3

cluster: n1 n2 n3
n2 and n3 are at the new version which has VIEW_VIRTUAL_COLUMNS
n1 is at the old version
restarting n1 fails

```
INFO  2019-04-25 17:24:44,398 [shard 0] storage_service - load_peer_features: peer=127.0.0.2, supported_features=CORRECT_COUNTER_ORDER,CORRECT_NON_COMPOUND_RANGE_TOMBSTONES,CORRECT_STATIC_COMPACT_IN_MC,COUNTERS,DIGEST_MULTIPARTITION_READ,INDEXES,LARGE_PARTITIONS,LA_SSTABLE_FORMAT,MATERIALIZED_VIEWS,MC_SSTABLE_FORMAT,RANGE_TOMBSTONES,ROLES,ROW_LEVEL_REPAIR,SCHEMA_TABLES_V3,STREAM_WITH_RPC_STREAM,TRUNCATION_TABLE,VIEW_VIRTUAL_COLUMNS,WRITE_FAILURE_REPLY,XXHASH
INFO  2019-04-25 17:24:44,398 [shard 0] storage_service - load_peer_features: peer=127.0.0.3, supported_features=CORRECT_COUNTER_ORDER,CORRECT_NON_COMPOUND_RANGE_TOMBSTONES,CORRECT_STATIC_COMPACT_IN_MC,COUNTERS,DIGEST_MULTIPARTITION_READ,INDEXES,LARGE_PARTITIONS,LA_SSTABLE_FORMAT,MATERIALIZED_VIEWS,MC_SSTABLE_FORMAT,RANGE_TOMBSTONES,ROLES,ROW_LEVEL_REPAIR,SCHEMA_TABLES_V3,STREAM_WITH_RPC_STREAM,TRUNCATION_TABLE,VIEW_VIRTUAL_COLUMNS,WRITE_FAILURE_REPLY,XXHASH
INFO  2019-04-25 17:24:44,398 [shard 0] storage_service - Checking remote features with system table, since this node is the only seed node
ERROR 2019-04-25 17:24:44,398 [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Feature check failed. This node can not join the cluster because it does not understand the feature. Local node 127.0.0.1 features = {CORRECT_COUNTER_ORDER, CORRECT_NON_COMPOUND_RANGE_TOMBSTONES, COUNTERS, DIGEST_MULTIPARTITION_READ, INDEXES, LARGE_PARTITIONS, LA_SSTABLE_FORMAT, MATERIALIZED_VIEWS, RANGE_TOMBSTONES, ROLES, SCHEMA_TABLES_V3, STREAM_WITH_RPC_STREAM, WRITE_FAILURE_REPLY, XXHASH}, Remote common_features = {CORRECT_COUNTER_ORDER, CORRECT_NON_COMPOUND_RANGE_TOMBSTONES, CORRECT_STATIC_COMPACT_IN_MC, COUNTERS, DIGEST_MULTIPARTITION_READ, INDEXES, LARGE_PARTITIONS, LA_SSTABLE_FORMAT, MATERIALIZED_VIEWS, MC_SSTABLE_FORMAT, RANGE_TOMBSTONES, ROLES, ROW_LEVEL_REPAIR, SCHEMA_TABLES_V3, STREAM_WITH_RPC_STREAM, TRUNCATION_TABLE, VIEW_VIRTUAL_COLUMNS, WRITE_FAILURE_REPLY, XXHASH})
```

@asias Why do we do a feature check when starting a node which is already part of the cluster?

**Comment by slivne** [comment]
We need to support rollback - rollback requires stopping a node and
starting with an older version.

Restarting of nodes is a subset of that.

**Comment by tgrabiec** [comment]
The workaround is to remove `system.peers` sstables from disk. Assuming there are other nodes running, it should repopulate. This is in general unsafe because it leaves the ring inconsistent for some time.

**Comment by slivne** [comment]
We need to check that a node is not booted into a cluster that has features it does not support.

Maybe we should instruct the users to start upgrade from seed nodes 

We instruct users in rollback to restore old system tables - so if the order was seeds first and then non seed nodes - at least the rollback procedure would be correct.

https://docs.scylladb.com/upgrade/upgrade-opensource/upgrade-guide-from-2.3-to-3.0/upgrade-guide-from-2.3-to-3.0-rpm/#restore-system-tables

**Comment by tgrabiec** [comment]
I don't see how starting the upgrade from the seed nodes helps for this issue. n1 could be a non-seed and it should fail because of the same reason.

**Comment by tgrabiec** [comment]
Currently, by definition, a cluster supports a feature when all members support it. So if we have an old member, the cluster doesn't support any new features yet. Looking only at other nodes is wrong.

If we wanted to prevent downgrading a node while the cluster is already fully upgraded, then we should have introduced another application state (e.g ENABLED_FEATURES), which would be set by each node when it notices that the whole cluster supports given feature. Then the booting node could examine ENABLED_FEATURES against its SUPPORTED_FEATURES.

**Comment by slivne** [comment]
@asias - please provide your view

**Comment by slivne** [comment]
@asias ping

**Comment by asias** [comment]
> @asias Why do we do a feature check when starting a node which is already part of the cluster?

To prevent node with old binary to the cluster. A node is already part of the cluster might be downgraded accidentally by admin and restarts into the cluster.

**Comment by asias** [comment]
> Currently, by definition, a cluster supports a feature when all members support it. So if we have an old member, the cluster doesn't support any new features yet. Looking only at other nodes is wrong.

Note, in your example, n1 is the only seed node, it could not talk to another seed node in the shadow round to get the live information what features are enabled in the cluster. Even if it does, all the other nodes will say it supports VIEW_VIRTUAL_COLUMNS. Now, n1 looking at itself, it says it does not support VIEW_VIRTUAL_COLUMNS. I think it is on the safe side to reject the restart. 

To continue the upgrade, one should restart n1 with new binary. 
To roll back the upgrade, one should roll back n2 and n3, then restarts n1. This won't help if n1 is the only seed node though. In the shadow round, we probably need to talk to all the nodes instead of only just the seed node, which is a good direction to eliminate the concept of seed.

**Comment by tgrabiec** [comment]
On Mon, May 20, 2019 at 9:58 AM Asias He <notifications@github.com> wrote:

> Currently, by definition, a cluster supports a feature when all members
> support it. So if we have an old member, the cluster doesn't support any
> new features yet. Looking only at other nodes is wrong.
>
> Note, in your example, n1 is the only seed node, it could not talk to
> another seed node in the shadow round to get the live information what
> features are enabled in the cluster. Even if it does, all the other nodes
> will say it supports VIEW_VIRTUAL_COLUMNS. Now, n1 looking at itself, it
> says it does not support VIEW_VIRTUAL_COLUMNS. I think it is on the safe
> side to reject the restart.
>
It may be on the safe side, but it's still a problem.

> To continue the upgrade, one should restart n1 with new binary.
> To roll back the upgrade, one should roll back n2 and n3, then restarts n1.
>
You cannot expect users to bring n2 down while n1 is down, as this may
cause unavailability.

> This won't help if n1 is the only seed node though. In the shadow round,
> we probably need to talk to all the nodes instead of only just the seed
> node, which is a good direction to eliminate the concept of seed.
>


>

**Comment by asias** [comment]
> On Mon, May 20, 2019 at 9:58 AM Asias He ***@***.***> wrote: Currently, by definition, a cluster supports a feature when all members support it. So if we have an old member, the cluster doesn't support any new features yet. Looking only at other nodes is wrong. Note, in your example, n1 is the only seed node, it could not talk to another seed node in the shadow round to get the live information what features are enabled in the cluster. Even if it does, all the other nodes will say it supports VIEW_VIRTUAL_COLUMNS. Now, n1 looking at itself, it says it does not support VIEW_VIRTUAL_COLUMNS. I think it is on the safe side to reject the restart.
> It may be on the safe side, but it's still a problem.

Be safe is better than being less safe in order to support a corner case. The problem happens only when you want to restart the *last* old node. I have provided a solution to this case as well. 

> To continue the upgrade, one should restart n1 with new binary. To roll back the upgrade, one should roll back n2 and n3, then restarts n1.
> You cannot expect users to bring n2 down while n1 is down, as this may cause unavailability.
> […](#)

Before restarting n1, user can roll back n2 first, then restart n1 will succeed. 

The only limitation is that the last old node is dead already. User has to start with the new binary. 

For this corner case and other cases where the features bit is messed up, we can introduce an option --disable-gossip-feature-check-during-boot in case the admin knows for sure what the versions are running in the cluster.

**Comment by tgrabiec** [comment]
> > On Mon, May 20, 2019 at 9:58 AM Asias He _**@**_.***> wrote: Currently, by definition, a cluster supports a feature when all members support it. So if we have an old member, the cluster doesn't support any new features yet. Looking only at other nodes is wrong. Note, in your example, n1 is the only seed node, it could not talk to another seed node in the shadow round to get the live information what features are enabled in the cluster. Even if it does, all the other nodes will say it supports VIEW_VIRTUAL_COLUMNS. Now, n1 looking at itself, it says it does not support VIEW_VIRTUAL_COLUMNS. I think it is on the safe side to reject the restart.
> > It may be on the safe side, but it's still a problem.
> 
> Be safe is better than being less safe in order to support a corner case. The problem happens only when you want to restart the _last_ old node. I have provided a solution to this case as well.

I don't think that forcing the user to upgrade n1 or bringing 2 nodes down are acceptable solutions. 

Restarts can happen without users initiating them, on a crash for example. When a user experiences a crash during the upgrade, forcing them to complete the upgrade is very risky, as rollbacks are not always possible once the cluster is fully upgraded. Also, upgrades after unclean restarts (with commitlog files left) are not always supported. In some cases, we required clean shutdown before upgrading.

Bringing 2 nodes down is not acceptable because it may cause unavailability or impact performance.

Any manual intervention is bad.

At any given moment during the upgrade, any node should be able to restart successfully without extra intervention. 

We shouldn't be looking at seeds at all during restart, only during bootstrap. Nodes that joined the cluster keep their peers in the system.peers table.

> 
> > To continue the upgrade, one should restart n1 with new binary. To roll back the upgrade, one should roll back n2 and n3, then restarts n1.
> > You cannot expect users to bring n2 down while n1 is down, as this may cause unavailability.
> > […](#)
> 
> Before restarting n1, user can roll back n2 first, then restart n1 will succeed.
> 
> The only limitation is that the last old node is dead already. User has to start with the new binary.
> 
> For this corner case and other cases where the features bit is messed up, we can introduce an option --disable-gossip-feature-check-during-boot in case the admin knows for sure what the versions are running in the cluster.

We could have a flag as the last resort, but we should not require this for expected situations. Restarts during the upgrade are expected and should not require manual intervention. So I think we should fix the feature checking. I suggested one possible solution in this thread.

**Comment by slivne** [comment]
@tgrabiec can you please provide a design so we will move all the features to a safer format.

We have done so in some (and I am not sure its done in the same way) - I would rather have a design and dictate that all work in the same manner and fix the old ones as well.

Thanks,

**Comment by tgrabiec** [comment]
Here's what I suggest.

Instead of looking at other nodes only when doing the feature check on restart, we should consider the current node from before the restart as well. We should therefore remember the set of advertised features of a node, after they passed the feature check, and consider that set on boot when calculating cluster’s potentially enabled features. We already remember supported features in system.local, they’re recorded before they pass the feature check though. We should move this after the check, so that only features which we could have already advertised are considered.

It’s not enough to remember the set of enabled features (which we don’t do yet) and compare node’s supported features against that on boot. This is prone to the problem that the restarting node’s view on enabled features could lag behind cluster’s enabled features, and may incorrectly allow downgrading a node.

Remembering supported features also allows us to avoid the feature check in most cases altogether. If new supported features contain at least what was there before, then invariant F must be preserved because monotonicity of supported features is preserved. We can avoid the shadow round. Only if monotonicity is broken do we make a more expensive check.

**Comment by kostja** [comment]
@tgrabiec This is solved by persisting the supported features. Now, with the new test.py machinery we could in theory test this, but I believe it still would be difficult (cross-version testing, or we'll have to add a special "test" feature enabled with a command line option just for the sake of testing, which I think is an overkill).
Agree to close this?

**Comment by tgrabiec** [comment]
Which commit do you think fixes this?

**Comment by kostja** [comment]
@tgrabiec the commit which persists cluster features  0df14a48cf1dec07df5c7530f6cc84cbb8a49600 and #4458 in general. We now are expected to fail in such case, so it's desired behaviour.

**Comment by tgrabiec** [comment]
If I add a new feature now, and hit the scenario mentioned in the first post during rolling upgrade, we will still fail in the same way, aren't we?

https://github.com/scylladb/scylladb/commit/0df14a48cf1dec07df5c7530f6cc84cbb8a49600 doesn't change the feature check which is the source of the "Feature check failed" error.

**Comment by kostja** [comment]
Any new feature we add now would be added the same way as we add e.g. RAFT feature - in a two-step procedure, first - declare support, then actually enable. It was impossible before, this is why the implementors had no choice but to enable the feature in new nodes as soon as they start, and this would lead to the situation you observed in this ticket.

Or do you have a better idea how we can enable the feature in a single step and still not break the case you describe?

**Comment by tgrabiec** [comment]
I'm not sure what you mean by "it was impossible before". "declare support, then, after all nodes in the cluster confirm the support, actually enable" is how cluster features always worked. We didn't persist locally the fact that the feature was observed to be enabled, it was inferred from gossip after restart. 

The scenario in this issue is when the feature wasn't enabled yet, because the upgrade is not completed in the cluster. We want it to remain not enabled in this state. The problem is that if you restart the old node, it thinks (incorrectly) that the feature is enabled, based on the state of other nodes in gossip.

**Comment by kbr-scylla** [comment]
I think this is fixed in Raft-based topology mode, need to check.
