### ISSUE TITLE
Docker image fails with IO errors on podman 1.8.2

### ISSUE THREAD

**Issue by dekimir** [scylladb/scylla#6199]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): unknown
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Fedora 31

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): docker
Hardware: two different machines, both AMD and Intel
Disks: (SSD/HDD, count) 1 HDD

With podman 1.8.2, I followed the instructions on the [getting-started](https://www.scylladb.com/download/open-source/#docker) page, but Scylla wouldn't start.  This happened on two different Fedora 31 machines, one desktop and one laptop.  Logs below:

```bash
localhost>cat /etc/redhat-release 
Fedora release 31 (Thirty One)
localhost>type podman
podman is /usr/bin/podman
localhost>podman --version 
podman version 1.8.2
localhost>podman run --name scylla -d scylladb/scylla
Trying to pull docker.io/scylladb/scylla...
Getting image source signatures
Copying blob ab5ef0e58194 done  
Copying blob 89e0cd6f40fc done  
Copying blob fe18da97d747 done  
Copying blob b78af7e0340c done  
Copying blob d176f30d01a6 done  
Copying blob 75fc199bc3f6 done  
Copying blob 9422d6902f00 done  
Copying blob 93f6ed4957ae done  
Copying blob d3f1ce5513b6 done  
Copying blob a25c56b097a3 done  
Copying blob ced610b15dee done  
Copying blob edcf991c163f done  
Copying blob c4470fca2bcd done  
Copying blob f7aad41f769b done  
Copying blob cfd50d5b29e2 done  
Copying blob 88a2bc837c51 done  
Copying blob 2be571b13a24 done  
Copying blob d7dc7428b5e4 done  
Copying blob fa7829918846 done  
Copying config 3a7728efd4 done  
Writing manifest to image destination
Storing signatures
6069be10481b046ec9c5d9847b86aa699dd28189759cabe85f16a35b6b553cd8
localhost>podman logs 6069be10481b 
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '1'],)
running: (['/opt/scylladb/scripts/scylla_io_setup'],)
2020-04-14 16:04:55,990 CRIT Supervisor running as root (no user in config file)
2020-04-14 16:04:55,990 WARN Included extra file "/etc/supervisord.conf.d/scylla-server.conf" during parsing
2020-04-14 16:04:55,990 WARN Included extra file "/etc/supervisord.conf.d/scylla-housekeeping.conf" during parsing
2020-04-14 16:04:55,990 WARN Included extra file "/etc/supervisord.conf.d/sshd-server.conf" during parsing
2020-04-14 16:04:55,990 WARN Included extra file "/etc/supervisord.conf.d/scylla-jmx.conf" during parsing
2020-04-14 16:04:55,990 WARN Included extra file "/etc/supervisord.conf.d/node-exporter.conf" during parsing
2020-04-14 16:04:56,007 INFO RPC interface 'supervisor' initialized
2020-04-14 16:04:56,007 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2020-04-14 16:04:56,007 INFO supervisord started with pid 21
2020-04-14 16:04:57,011 INFO spawned: 'scylla-jmx' with pid 24
2020-04-14 16:04:57,015 INFO spawned: 'scylla' with pid 25
2020-04-14 16:04:57,017 INFO spawned: 'node-exporter' with pid 26
2020-04-14 16:04:57,019 INFO spawned: 'sshd' with pid 27
2020-04-14 16:04:57,021 INFO spawned: 'scylla-housekeeping' with pid 28
time="2020-04-14T16:04:57Z" level=info msg="Starting node_exporter (version=0.17.0, branch=HEAD, revision=f6f6194a436b9a63d0439abc585c76b19a206b21)" source="node_exporter.go:82"
time="2020-04-14T16:04:57Z" level=info msg="Build context (go=go1.11.2, user=root@322511e06ced, date=20181130-15:51:33)" source="node_exporter.go:83"
time="2020-04-14T16:04:57Z" level=info msg="Enabled collectors:" source="node_exporter.go:90"
time="2020-04-14T16:04:57Z" level=info msg=" - arp" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - bcache" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - bonding" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - conntrack" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - cpu" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - diskstats" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - edac" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - entropy" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - filefd" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - filesystem" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - hwmon" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - infiniband" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - interrupts" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - ipvs" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - loadavg" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - mdadm" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - meminfo" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - netclass" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - netdev" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - netstat" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - nfs" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - nfsd" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - sockstat" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - stat" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - textfile" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - time" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - timex" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - uname" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - vmstat" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - xfs" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg=" - zfs" source="node_exporter.go:97"
time="2020-04-14T16:04:57Z" level=info msg="Listening on :9100" source="node_exporter.go:111"
Generating public/private ed25519 key pair.
Your identification has been saved in /etc/ssh/ssh_host_ed25519_key.
Your public key has been saved in /etc/ssh/ssh_host_ed25519_key.pub.
The key fingerprint is:
SHA256:1Wre43ZunefH+VZyGezV4f/0VLIzNSQFyuVjIoWrNTk root@6069be10481b
The key's randomart image is:
+--[ED25519 256]--+
|          .. oo. |
|         .o.+. o |
|         .++.+= o|
|         E..o o==|
|        S =   .+B|
|       . o .  =o*|
|          . o  X*|
|           ...ooO|
|           ..+.o*|
+----[SHA256]-----+
Scylla version 3.3.0-0.20200319.7ae2cdf46c7 with build-id e1a6c0b608140610f1e783632d61f1f2c7fb932d starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 10.0.2.100 --rpc-address 10.0.2.100 --seed-provider-parameters seeds=10.0.2.100 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 10.0.2.100, rpc-address: 10.0.2.100, seed-provider-parameters: seeds=10.0.2.100, blocked-reactor-notify-ms: 999999999]
WARN  2020-04-14 16:04:57,239 seastar - Couldn't read cgroup file /sys/fs/cgroup/cpuset/cpuset.cpus.
WARN  2020-04-14 16:04:57,240 seastar - Unable to parse cgroup's cpuset. Ignoring.
WARN  2020-04-14 16:04:57,252 seastar - Couldn't read cgroup file /sys/fs/cgroup/memory/memory.limit_in_bytes.
WARN  2020-04-14 16:04:57,278 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
INFO  2020-04-14 16:04:57,294 [shard 0] init - installing SIGHUP handler
INFO  2020-04-14 16:04:57,304 [shard 0] init - Scylla version 3.3.0-0.20200319.7ae2cdf46c7 with build-id e1a6c0b608140610f1e783632d61f1f2c7fb932d starting ...

WARN  2020-04-14 16:04:57,304 [shard 0] init - NOFILE rlimit too low (recommended setting 200000, minimum setting 10000; you may run out of file descriptors.
INFO  2020-04-14 16:04:57,305 [shard 0] init - starting prometheus API server
INFO  2020-04-14 16:04:57,308 [shard 0] init - starting migration manager notifier
INFO  2020-04-14 16:04:57,309 [shard 0] init - creating tracing
INFO  2020-04-14 16:04:57,312 [shard 0] init - creating snitch
INFO  2020-04-14 16:04:57,312 [shard 0] init - determining DNS name
INFO  2020-04-14 16:04:57,312 [shard 0] init - starting API server
INFO  2020-04-14 16:04:57,312 [shard 0] init - Scylla API server listening on 127.0.0.1:10000 ...
INFO  2020-04-14 16:04:57,313 [shard 0] init - initializing storage service
INFO  2020-04-14 16:04:57,313 [shard 0] init - starting per-shard database core
WARN  2020-04-14 16:04:57,316 [shard 0] init - I/O Scheduler is not properly configured! This is a non-supported setup, and performance is expected to be unpredictably bad.
 Reason found: none of --max-io-requests, --io-properties and --io-properties-file are set.
To properly configure the I/O Scheduler, run the scylla_io_setup utility shipped with Scylla.

INFO  2020-04-14 16:04:57,317 [shard 0] init - creating and verifying directories
WARN  2020-04-14 16:04:57,321 [shard 0] storage_service - Shutting down communications due to I/O errors until operator intervention
WARN  2020-04-14 16:04:57,321 [shard 0] storage_service - Disk error: std::system_error (error system:75, Value too large for defined data type)
INFO  2020-04-14 16:04:57,321 [shard 0] storage_service - Stop transport: starts
INFO  2020-04-14 16:04:57,321 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2020-04-14 16:04:57,321 [shard 0] gossip - gossip is already stopped
INFO  2020-04-14 16:04:57,321 [shard 0] storage_service - Stop transport: stop_gossiping done
INFO  2020-04-14 16:04:57,321 [shard 0] storage_service - messaging_service stopped
INFO  2020-04-14 16:04:57,321 [shard 0] storage_service - Stop transport: shutdown messaging_service done
INFO  2020-04-14 16:04:57,321 [shard 0] storage_service - stream_manager stopped
INFO  2020-04-14 16:04:57,321 [shard 0] storage_service - Stop transport: shutdown stream_manager done
INFO  2020-04-14 16:04:57,321 [shard 0] storage_service - Stop transport: auth shutdown
INFO  2020-04-14 16:04:57,321 [shard 0] storage_service - Stop transport: done
ERROR 2020-04-14 16:04:57,321 [shard 0] init - Directory '"/var/lib/scylla/commitlog"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:57,322 [shard 0] init - Directory '"/var/lib/scylla/data"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:57,322 [shard 0] init - Directory '"/var/lib/scylla/hints/1"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:57,322 [shard 0] init - Directory '"/var/lib/scylla/hints/0"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:57,323 [shard 0] init - Directory '"/var/lib/scylla/hints/5"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:57,323 [shard 0] init - Directory '"/var/lib/scylla/view_hints/0"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:57,323 [shard 0] init - Directory '"/var/lib/scylla/hints/2"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:57,323 [shard 0] init - Directory '"/var/lib/scylla/view_hints/1"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:57,323 [shard 0] init - Directory '"/var/lib/scylla/hints/3"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:57,324 [shard 0] init - Directory '"/var/lib/scylla/view_hints/2"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:57,324 [shard 0] init - Directory '"/var/lib/scylla/hints/4"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:57,324 [shard 0] init - Directory '"/var/lib/scylla/view_hints/3"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:57,324 [shard 0] init - Directory '"/var/lib/scylla/view_hints/4"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:57,324 [shard 0] init - Directory '"/var/lib/scylla/view_hints/5"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:57,324 [shard 0] init - Directory '"/var/lib/scylla/view_hints/6"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:57,324 [shard 0] init - Directory '"/var/lib/scylla/hints/7"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:57,324 [shard 0] init - Directory '"/var/lib/scylla/hints/6"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:57,324 [shard 0] init - Directory '"/var/lib/scylla/view_hints/7"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
INFO  2020-04-14 16:04:57,324 [shard 0] init - Shutting down database
INFO  2020-04-14 16:04:57,325 [shard 0] init - Shutting down database: waiting for background jobs...
INFO  2020-04-14 16:04:57,325 [shard 0] init - Shutting down database was successful
INFO  2020-04-14 16:04:57,325 [shard 0] init - Shutting down migration manager notifier
INFO  2020-04-14 16:04:57,325 [shard 0] init - Shutting down migration manager notifier was successful
INFO  2020-04-14 16:04:57,325 [shard 0] init - Shutting down prometheus API server
INFO  2020-04-14 16:04:57,325 [shard 0] init - Shutting down prometheus API server was successful
INFO  2020-04-14 16:04:57,325 [shard 0] init - Shutting down sighup
INFO  2020-04-14 16:04:57,325 [shard 0] init - Shutting down sighup was successful
INFO  2020-04-14 16:04:57,326 [shard 0] init - Startup failed: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
2020-04-14 16:04:57,340 INFO exited: scylla (exit status 1; not expected)
Generating public/private rsa key pair.
Your identification has been saved in /etc/ssh/ssh_host_rsa_key.
Your public key has been saved in /etc/ssh/ssh_host_rsa_key.pub.
The key fingerprint is:
SHA256:la0IttQR9FSJTlV3sgqewk2xNZcQyt8+o1/8ThvcK7g root@6069be10481b
The key's randomart image is:
+---[RSA 4096]----+
|       .+.o+B=+.o|
|       . =oB.o.+.|
|      + .oX . .  |
|     o + *.= o   |
|      . S = o .  |
|         .   ....|
|            . +o=|
|           . o ==|
|           Eo.o+o|
+----[SHA256]-----+
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Connecting to http://localhost:10000
Starting the JMX server
JMX is enabled to receive remote connections on port: 7199
2020-04-14 16:04:58,607 INFO success: scylla-jmx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-14 16:04:58,611 INFO spawned: 'scylla' with pid 85
2020-04-14 16:04:58,612 INFO success: node-exporter entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-14 16:04:58,613 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-14 16:04:58,613 INFO success: scylla-housekeeping entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Scylla version 3.3.0-0.20200319.7ae2cdf46c7 with build-id e1a6c0b608140610f1e783632d61f1f2c7fb932d starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 10.0.2.100 --rpc-address 10.0.2.100 --seed-provider-parameters seeds=10.0.2.100 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 10.0.2.100, rpc-address: 10.0.2.100, seed-provider-parameters: seeds=10.0.2.100, blocked-reactor-notify-ms: 999999999]
WARN  2020-04-14 16:04:58,810 seastar - Couldn't read cgroup file /sys/fs/cgroup/cpuset/cpuset.cpus.
WARN  2020-04-14 16:04:58,811 seastar - Unable to parse cgroup's cpuset. Ignoring.
WARN  2020-04-14 16:04:58,817 seastar - Couldn't read cgroup file /sys/fs/cgroup/memory/memory.limit_in_bytes.
WARN  2020-04-14 16:04:58,834 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
INFO  2020-04-14 16:04:58,852 [shard 0] init - installing SIGHUP handler
INFO  2020-04-14 16:04:58,859 [shard 0] init - Scylla version 3.3.0-0.20200319.7ae2cdf46c7 with build-id e1a6c0b608140610f1e783632d61f1f2c7fb932d starting ...

WARN  2020-04-14 16:04:58,859 [shard 0] init - NOFILE rlimit too low (recommended setting 200000, minimum setting 10000; you may run out of file descriptors.
INFO  2020-04-14 16:04:58,859 [shard 0] init - starting prometheus API server
INFO  2020-04-14 16:04:58,860 [shard 0] init - starting migration manager notifier
INFO  2020-04-14 16:04:58,860 [shard 0] init - creating tracing
INFO  2020-04-14 16:04:58,860 [shard 0] init - creating snitch
INFO  2020-04-14 16:04:58,860 [shard 0] init - determining DNS name
INFO  2020-04-14 16:04:58,860 [shard 0] init - starting API server
INFO  2020-04-14 16:04:58,861 [shard 0] init - Scylla API server listening on 127.0.0.1:10000 ...
INFO  2020-04-14 16:04:58,861 [shard 0] init - initializing storage service
INFO  2020-04-14 16:04:58,861 [shard 0] init - starting per-shard database core
WARN  2020-04-14 16:04:58,863 [shard 0] init - I/O Scheduler is not properly configured! This is a non-supported setup, and performance is expected to be unpredictably bad.
 Reason found: none of --max-io-requests, --io-properties and --io-properties-file are set.
To properly configure the I/O Scheduler, run the scylla_io_setup utility shipped with Scylla.

INFO  2020-04-14 16:04:58,863 [shard 0] init - creating and verifying directories
WARN  2020-04-14 16:04:58,870 [shard 0] storage_service - Shutting down communications due to I/O errors until operator intervention
WARN  2020-04-14 16:04:58,870 [shard 0] storage_service - Disk error: std::system_error (error system:75, Value too large for defined data type)
INFO  2020-04-14 16:04:58,870 [shard 0] storage_service - Stop transport: starts
INFO  2020-04-14 16:04:58,870 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2020-04-14 16:04:58,870 [shard 0] gossip - gossip is already stopped
INFO  2020-04-14 16:04:58,870 [shard 0] storage_service - Stop transport: stop_gossiping done
INFO  2020-04-14 16:04:58,870 [shard 0] storage_service - messaging_service stopped
INFO  2020-04-14 16:04:58,870 [shard 0] storage_service - Stop transport: shutdown messaging_service done
INFO  2020-04-14 16:04:58,870 [shard 0] storage_service - stream_manager stopped
INFO  2020-04-14 16:04:58,870 [shard 0] storage_service - Stop transport: shutdown stream_manager done
INFO  2020-04-14 16:04:58,870 [shard 0] storage_service - Stop transport: auth shutdown
INFO  2020-04-14 16:04:58,870 [shard 0] storage_service - Stop transport: done
ERROR 2020-04-14 16:04:58,870 [shard 0] init - Directory '"/var/lib/scylla/commitlog"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:58,871 [shard 0] init - Directory '"/var/lib/scylla/data"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:58,872 [shard 0] init - Directory '"/var/lib/scylla/view_hints/5"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:58,872 [shard 0] init - Directory '"/var/lib/scylla/hints/5"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:58,872 [shard 0] init - Directory '"/var/lib/scylla/hints/3"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:58,872 [shard 0] init - Directory '"/var/lib/scylla/hints/7"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:58,872 [shard 0] init - Directory '"/var/lib/scylla/view_hints/1"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:58,872 [shard 0] init - Directory '"/var/lib/scylla/hints/2"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:58,872 [shard 0] init - Directory '"/var/lib/scylla/hints/1"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:58,872 [shard 0] init - Directory '"/var/lib/scylla/hints/4"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:58,872 [shard 0] init - Directory '"/var/lib/scylla/view_hints/3"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:58,872 [shard 0] init - Directory '"/var/lib/scylla/view_hints/0"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:58,872 [shard 0] init - Directory '"/var/lib/scylla/hints/0"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:58,872 [shard 0] init - Directory '"/var/lib/scylla/view_hints/4"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:58,872 [shard 0] init - Directory '"/var/lib/scylla/hints/6"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:58,872 [shard 0] init - Directory '"/var/lib/scylla/view_hints/2"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:58,872 [shard 0] init - Directory '"/var/lib/scylla/view_hints/7"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:04:58,873 [shard 0] init - Directory '"/var/lib/scylla/view_hints/6"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
INFO  2020-04-14 16:04:58,873 [shard 0] init - Shutting down database
INFO  2020-04-14 16:04:58,873 [shard 0] init - Shutting down database: waiting for background jobs...
INFO  2020-04-14 16:04:58,873 [shard 0] init - Shutting down database was successful
INFO  2020-04-14 16:04:58,873 [shard 0] init - Shutting down migration manager notifier
INFO  2020-04-14 16:04:58,874 [shard 0] init - Shutting down migration manager notifier was successful
INFO  2020-04-14 16:04:58,874 [shard 0] init - Shutting down prometheus API server
INFO  2020-04-14 16:04:58,874 [shard 0] init - Shutting down prometheus API server was successful
INFO  2020-04-14 16:04:58,874 [shard 0] init - Shutting down sighup
INFO  2020-04-14 16:04:58,874 [shard 0] init - Shutting down sighup was successful
INFO  2020-04-14 16:04:58,874 [shard 0] init - Startup failed: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
2020-04-14 16:04:58,898 INFO exited: scylla (exit status 1; not expected)
2020-04-14 16:05:00,904 INFO spawned: 'scylla' with pid 118
Scylla version 3.3.0-0.20200319.7ae2cdf46c7 with build-id e1a6c0b608140610f1e783632d61f1f2c7fb932d starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 10.0.2.100 --rpc-address 10.0.2.100 --seed-provider-parameters seeds=10.0.2.100 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 10.0.2.100, rpc-address: 10.0.2.100, seed-provider-parameters: seeds=10.0.2.100, blocked-reactor-notify-ms: 999999999]
WARN  2020-04-14 16:05:01,177 seastar - Couldn't read cgroup file /sys/fs/cgroup/cpuset/cpuset.cpus.
WARN  2020-04-14 16:05:01,177 seastar - Unable to parse cgroup's cpuset. Ignoring.
WARN  2020-04-14 16:05:01,180 seastar - Couldn't read cgroup file /sys/fs/cgroup/memory/memory.limit_in_bytes.
WARN  2020-04-14 16:05:01,204 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
INFO  2020-04-14 16:05:01,236 [shard 0] init - installing SIGHUP handler
INFO  2020-04-14 16:05:01,252 [shard 0] init - Scylla version 3.3.0-0.20200319.7ae2cdf46c7 with build-id e1a6c0b608140610f1e783632d61f1f2c7fb932d starting ...

WARN  2020-04-14 16:05:01,252 [shard 0] init - NOFILE rlimit too low (recommended setting 200000, minimum setting 10000; you may run out of file descriptors.
INFO  2020-04-14 16:05:01,253 [shard 0] init - starting prometheus API server
INFO  2020-04-14 16:05:01,255 [shard 0] init - starting migration manager notifier
INFO  2020-04-14 16:05:01,255 [shard 0] init - creating tracing
INFO  2020-04-14 16:05:01,256 [shard 0] init - creating snitch
INFO  2020-04-14 16:05:01,257 [shard 0] init - determining DNS name
INFO  2020-04-14 16:05:01,257 [shard 0] init - starting API server
INFO  2020-04-14 16:05:01,258 [shard 0] init - Scylla API server listening on 127.0.0.1:10000 ...
INFO  2020-04-14 16:05:01,259 [shard 0] init - initializing storage service
INFO  2020-04-14 16:05:01,259 [shard 0] init - starting per-shard database core
WARN  2020-04-14 16:05:01,266 [shard 0] init - I/O Scheduler is not properly configured! This is a non-supported setup, and performance is expected to be unpredictably bad.
 Reason found: none of --max-io-requests, --io-properties and --io-properties-file are set.
To properly configure the I/O Scheduler, run the scylla_io_setup utility shipped with Scylla.

INFO  2020-04-14 16:05:01,266 [shard 0] init - creating and verifying directories
WARN  2020-04-14 16:05:01,594 [shard 0] storage_service - Shutting down communications due to I/O errors until operator intervention
WARN  2020-04-14 16:05:01,594 [shard 0] storage_service - Disk error: std::system_error (error system:75, Value too large for defined data type)
INFO  2020-04-14 16:05:01,594 [shard 0] storage_service - Stop transport: starts
ERROR 2020-04-14 16:05:01,594 [shard 0] init - Directory '"/var/lib/scylla/data"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
INFO  2020-04-14 16:05:01,594 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2020-04-14 16:05:01,594 [shard 0] gossip - gossip is already stopped
ERROR 2020-04-14 16:05:01,594 [shard 0] init - Directory '"/var/lib/scylla/commitlog"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
INFO  2020-04-14 16:05:01,594 [shard 0] storage_service - Stop transport: stop_gossiping done
INFO  2020-04-14 16:05:01,594 [shard 0] storage_service - messaging_service stopped
INFO  2020-04-14 16:05:01,594 [shard 0] storage_service - Stop transport: shutdown messaging_service done
INFO  2020-04-14 16:05:01,595 [shard 0] storage_service - stream_manager stopped
INFO  2020-04-14 16:05:01,595 [shard 0] storage_service - Stop transport: shutdown stream_manager done
INFO  2020-04-14 16:05:01,595 [shard 0] storage_service - Stop transport: auth shutdown
INFO  2020-04-14 16:05:01,595 [shard 0] storage_service - Stop transport: done
ERROR 2020-04-14 16:05:01,597 [shard 0] init - Directory '"/var/lib/scylla/hints/1"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:05:01,597 [shard 0] init - Directory '"/var/lib/scylla/hints/2"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:05:01,598 [shard 0] init - Directory '"/var/lib/scylla/hints/0"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:05:01,598 [shard 0] init - Directory '"/var/lib/scylla/hints/4"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:05:01,598 [shard 0] init - Directory '"/var/lib/scylla/hints/3"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:05:01,599 [shard 0] init - Directory '"/var/lib/scylla/hints/6"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:05:01,599 [shard 0] init - Directory '"/var/lib/scylla/hints/5"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:05:01,599 [shard 0] init - Directory '"/var/lib/scylla/view_hints/0"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:05:01,600 [shard 0] init - Directory '"/var/lib/scylla/view_hints/2"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:05:01,600 [shard 0] init - Directory '"/var/lib/scylla/hints/7"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:05:01,600 [shard 0] init - Directory '"/var/lib/scylla/view_hints/1"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:05:01,601 [shard 0] init - Directory '"/var/lib/scylla/view_hints/5"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:05:01,601 [shard 0] init - Directory '"/var/lib/scylla/view_hints/6"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:05:01,601 [shard 0] init - Directory '"/var/lib/scylla/view_hints/3"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:05:01,602 [shard 0] init - Directory '"/var/lib/scylla/view_hints/4"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:05:01,602 [shard 0] init - Directory '"/var/lib/scylla/view_hints/7"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
INFO  2020-04-14 16:05:01,602 [shard 0] init - Shutting down database
INFO  2020-04-14 16:05:01,604 [shard 0] init - Shutting down database: waiting for background jobs...
INFO  2020-04-14 16:05:01,604 [shard 0] init - Shutting down database was successful
INFO  2020-04-14 16:05:01,605 [shard 0] init - Shutting down migration manager notifier
INFO  2020-04-14 16:05:01,606 [shard 0] init - Shutting down migration manager notifier was successful
INFO  2020-04-14 16:05:01,606 [shard 0] init - Shutting down prometheus API server
INFO  2020-04-14 16:05:01,607 [shard 0] init - Shutting down prometheus API server was successful
INFO  2020-04-14 16:05:01,607 [shard 0] init - Shutting down sighup
INFO  2020-04-14 16:05:01,608 [shard 0] init - Shutting down sighup was successful
INFO  2020-04-14 16:05:01,609 [shard 0] init - Startup failed: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
2020-04-14 16:05:01,637 INFO exited: scylla (exit status 1; not expected)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/opt/scylladb/python3/lib64/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/opt/scylladb/python3/lib64/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scylladb/python3/lib64/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 64, in get_url
    return urllib.request.urlopen(path).read().decode('utf-8')
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 1347, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 1321, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 197, in <module>
    args.func(args)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 123, in check_version
    current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 82, in get_api
    return get_json_from_url("http://" + api_address + path)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 74, in get_json_from_url
    retval = result.get(timeout=5)
  File "/opt/scylladb/python3/lib64/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
2020-04-14 16:05:05,569 INFO spawned: 'scylla' with pid 163
Scylla version 3.3.0-0.20200319.7ae2cdf46c7 with build-id e1a6c0b608140610f1e783632d61f1f2c7fb932d starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 10.0.2.100 --rpc-address 10.0.2.100 --seed-provider-parameters seeds=10.0.2.100 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 10.0.2.100, rpc-address: 10.0.2.100, seed-provider-parameters: seeds=10.0.2.100, blocked-reactor-notify-ms: 999999999]
WARN  2020-04-14 16:05:05,782 seastar - Couldn't read cgroup file /sys/fs/cgroup/cpuset/cpuset.cpus.
WARN  2020-04-14 16:05:05,782 seastar - Unable to parse cgroup's cpuset. Ignoring.
WARN  2020-04-14 16:05:05,787 seastar - Couldn't read cgroup file /sys/fs/cgroup/memory/memory.limit_in_bytes.
WARN  2020-04-14 16:05:05,831 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
INFO  2020-04-14 16:05:05,855 [shard 0] init - installing SIGHUP handler
INFO  2020-04-14 16:05:05,862 [shard 0] init - Scylla version 3.3.0-0.20200319.7ae2cdf46c7 with build-id e1a6c0b608140610f1e783632d61f1f2c7fb932d starting ...

WARN  2020-04-14 16:05:05,862 [shard 0] init - NOFILE rlimit too low (recommended setting 200000, minimum setting 10000; you may run out of file descriptors.
INFO  2020-04-14 16:05:05,862 [shard 0] init - starting prometheus API server
INFO  2020-04-14 16:05:05,863 [shard 0] init - starting migration manager notifier
INFO  2020-04-14 16:05:05,863 [shard 0] init - creating tracing
INFO  2020-04-14 16:05:05,863 [shard 0] init - creating snitch
INFO  2020-04-14 16:05:05,863 [shard 0] init - determining DNS name
INFO  2020-04-14 16:05:05,863 [shard 0] init - starting API server
INFO  2020-04-14 16:05:05,864 [shard 0] init - Scylla API server listening on 127.0.0.1:10000 ...
INFO  2020-04-14 16:05:05,864 [shard 0] init - initializing storage service
INFO  2020-04-14 16:05:05,864 [shard 0] init - starting per-shard database core
WARN  2020-04-14 16:05:05,866 [shard 0] init - I/O Scheduler is not properly configured! This is a non-supported setup, and performance is expected to be unpredictably bad.
 Reason found: none of --max-io-requests, --io-properties and --io-properties-file are set.
To properly configure the I/O Scheduler, run the scylla_io_setup utility shipped with Scylla.

INFO  2020-04-14 16:05:05,866 [shard 0] init - creating and verifying directories
WARN  2020-04-14 16:05:05,876 [shard 0] storage_service - Shutting down communications due to I/O errors until operator intervention
WARN  2020-04-14 16:05:05,876 [shard 0] storage_service - Disk error: std::system_error (error system:75, Value too large for defined data type)
INFO  2020-04-14 16:05:05,876 [shard 0] storage_service - Stop transport: starts
ERROR 2020-04-14 16:05:05,876 [shard 0] init - Directory '"/var/lib/scylla/data"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
ERROR 2020-04-14 16:05:05,876 [shard 0] init - Directory '"/var/lib/scylla/commitlog"' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 75: Value too large for defined data type)
INFO  2020-04-14 16:05:05,877 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
```

**Comment by dorlaor** [comment]
I have a similar issue, some scylla releases do work, and some (nightly) do not.

**Comment by penberg** [comment]
The issue is that `read`, `lseek` or some other system call is failing with `EOVERFLOW`:

```
WARN  2020-04-14 16:04:58,870 [shard 0] storage_service - Disk error: std::system_error (error system:75, Value too large for defined data type)
```

This could be a Scylla bug or some issue with whatever `podman` uses for storage.

**Comment by penberg** [comment]
@dekimir @dorlaor What storage engine is your `podman` using? I think you can see that in the `$HOME/.config/containers/storage.conf` file.

**Comment by dekimir** [comment]
> @dekimir @dorlaor What storage engine is your `podman` using? I think you can see that in the `$HOME/.config/containers/storage.conf` file.

Is fuse-overlayfs a storage engine?  My config mentions it:
```bash
localhost>cat ~/.config/containers/storage.conf 
[storage]
  driver = "overlay"
  runroot = "/run/user/1000"
  graphroot = "/home/dejan/.local/share/containers/storage"
  [storage.options]
    size = ""
    remap-uids = ""
    remap-gids = ""
    ignore_chown_errors = ""
    remap-user = ""
    remap-group = ""
    mount_program = "/usr/bin/fuse-overlayfs"
    mountopt = ""
    [storage.options.thinpool]
      autoextend_percent = ""
      autoextend_threshold = ""
      basesize = ""
      blocksize = ""
      directlvm_device = ""
      directlvm_device_force = ""
      fs = ""
      log_level = ""
      min_free_space = ""
      mkfsarg = ""
      mountopt = ""
      use_deferred_deletion = ""
      use_deferred_removal = ""
      xfs_nospace_max_retries = ""
localhost>podman info
host:
  BuildahVersion: 1.14.3
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.14-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.14, commit: 083a0be12178013d44ff51ceda3090ea741b6516'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 99101286400
  MemTotal: 134993440768
  OCIRuntime:
    name: crun
    package: crun-0.13-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 4294963200
  SwapTotal: 4294963200
  arch: amd64
  cpus: 32
  eventlogger: journald
  hostname: localhost.localdomain
  kernel: 5.5.15-200.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 162h 10m 27.96s (Approximately 6.75 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /home/dejan/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.8-1.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.8
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/dejan/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /run/user/1000
  VolumePath: /home/dejan/.local/share/containers/storage/volumes

localhost>ll /home/dejan/.local/share/containers/storage/volumes
total 8
drwx------. 3 dejan dejan 4096 Apr 10 18:20 35182e26d11fd1993138205fc55011e32b5ddf3b8dd7fe6ada6acc54624c30ee/
drwx------. 3 dejan dejan 4096 Apr 10 18:00 0c9aa7c4ee5b32926cce5a93416580e980752cbb203363d900b43fa8524e8827/
localhost>du -sh /home/dejan/.local/share/containers/storage/volumes
572K	/home/dejan/.local/share/containers/storage/volumes
localhost>dnf provides /usr/bin/fuse-overlayfs
Last metadata expiration check: 6 days, 20:15:34 ago on Wed 08 Apr 2020 03:03:12 PM EDT.
fuse-overlayfs-0.6.4-2.fc31.x86_64 : FUSE overlay+shiftfs implementation for rootless containers
Repo        : fedora
Matched from:
Filename    : /usr/bin/fuse-overlayfs

fuse-overlayfs-0.7.8-1.fc31.x86_64 : FUSE overlay+shiftfs implementation for rootless containers
Repo        : @System
Matched from:
Filename    : /usr/bin/fuse-overlayfs

fuse-overlayfs-0.7.8-1.fc31.x86_64 : FUSE overlay+shiftfs implementation for rootless containers
Repo        : updates
Matched from:
Filename    : /usr/bin/fuse-overlayfs

localhost>dnf list fuse-overlayfs
Fedora Modular 31 - x86_64                                                                                                   33 kB/s |  17 kB     00:00    
Fedora Modular 31 - x86_64 - Updates                                                                                         42 kB/s |  16 kB     00:00    
Fedora Modular 31 - x86_64 - Updates                                                                                        269 kB/s | 203 kB     00:00    
Fedora 31 - x86_64 - Updates                                                                                                 34 kB/s |  14 kB     00:00    
Fedora 31 - x86_64 - Updates                                                                                                1.4 MB/s | 4.1 MB     00:02    
Fedora 31 - x86_64                                                                                                           34 kB/s |  17 kB     00:00    
google-chrome                                                                                                                15 kB/s | 1.3 kB     00:00    
google-chrome                                                                                                                15 kB/s | 3.4 kB     00:00    
RPM Fusion for Fedora 31 - Free - Updates                                                                                    13 kB/s | 3.6 kB     00:00    
RPM Fusion for Fedora 31 - Free - Updates                                                                                   428 kB/s | 416 kB     00:00    
RPM Fusion for Fedora 31 - Free                                                                                              11 kB/s | 3.2 kB     00:00    
Installed Packages
fuse-overlayfs.x86_64                                                         0.7.8-1.fc31                                                          @updates
localhost>
```

**Comment by avikivity** [comment]
The EOVERFLOW is due to a kernel bug, unapplied patch [here](https://lore.kernel.org/stable/20191128155940.17530-2-mszeredi@redhat.com/).

You can work around with --unsafe-bypass-fsync (a good idea when playing around regardless).

**Comment by avikivity** [comment]
Closing as this is not a Scylla bug.

**Comment by avikivity** [comment]
The patch hit linux-next, so you can expect it to start finding its way to distributions in a month or two.

**Comment by avikivity** [comment]
The fix landed in linux 5.7.3, 5.6.19, and 5.4.47.

**Comment by nyh** [comment]
> Closing as this is not a Scylla bug.

I think you are wrong and this issue should be reopened.
Not supporting a kernel that came out more than 3 days ago *is* a Scylla bug. Scylla should have worked around this known kernel bug. We can remove the workaround some period after the fixed kernels come out, but not *3 days* after came out - and definitely not, as was the case here - two months *before* the fix came out :-(

**Comment by avikivity** [comment]
We support those old kernels. We just don't support them with podman, and _without_ a data volume. It's just this combination that is broken.

I don't see how keeping the bug open helps, though.

**Comment by nyh** [comment]
Avi, the thing is that I just followed the "getting started" instructions we have all over the place - I ran Scylla inside "docker" on Fedora 32 (which is really podman - this is Fedora 32's "podman-docker" package, since the "docker" one doesn't work at all), and it failed on this obscure error.

You are right that *today*, just upgrading your kernel will work although it's still not exactly foolproof (I upgrade my kernel frequently, but mine still wasn't new enough!). But when you closed this issue, two months ago, it was before such kernel even existed. I think it was a mistake to decide not to work around this bug. And the reason why I'm saying this now is that I hope that next time we encounter a similar issue, the decision would be different.

**Comment by dekimir** [comment]
> I ran Scylla inside "docker" on Fedora 32 (which is really podman - this
> is Fedora 32's "podman-docker" package, since the "docker" one doesn't work
> at all)
>

FWIW, the package docker-ce works on F32.

https://linuxconfig.org/how-to-install-and-configure-docker-ce-moby-engine-on-fedora-32

**Comment by nyh** [comment]
@dekimir I didn't check "docker-ce". One of the reasons I didn't try it is that https://www.linuxuprising.com/2019/11/how-to-install-and-use-docker-on-fedora.html told me that docker-ce also doesn't work with containers v2. Maybe it does now?
In any case, even if it does work and runs Scylla, having two out of the three ways to install docker on Fedora 32 not be able to run Scylla's image isn't a very good track record :-)
As I said, I'm not trying to convince you or Avi that we need to fix anything now - certainly not now that the newest Fedora 32 kernel does work with podman, so it's just a matter of time until it will work for everyone. I'm trying to convince you of the principle here: That we need to follow Postel's law: We should make an effort for Scylla to run on many different setups, instead of 90% of the users encountering errors because we consider their one-month-old setup "buggy" or "too old".

**Comment by avikivity** [comment]
@nyh unfortunately few users run Fedora, and even with fedora+podman, the problem only occurs if you don't bind-mount a storage volume (which is the proper way to run a database).

**Comment by dekimir** [comment]
> 90% of the users encountering errors

Really, 90%?  How come they're not flooding us with feedback about it?

> if you don't bind-mount a storage volume (which is the proper way to run a database).

I suppose this might be common knowledge among certain professionals, but don't count on the average user knowing that.  Does our getting-started guide mention that this is the only proper way?  And if it does, how come @dorlaor , @nyh, and I managed to miss it?

**Comment by avikivity** [comment]
If you don't bind-mound a storage volume, you'll lose all your data once the container is restarted.

It is [documented](https://docs.scylladb.com/operating-scylla/procedures/tips/best_practices_scylla_on_docker/#configuring-a-data-volume-for-storage) (but says nothing about the default storage being volatile)

**Comment by avikivity** [comment]
(and likely users are using the "real" docker, not podman, it's only Scylla developers who are driven to use podman by our Fedora affinity + docker's disregard for the cgroupv2 change (which is five years old or so)).

**Comment by nyh** [comment]
> (and likely users are using the "real" docker, not podman, it's only Scylla developers who are driven to use podman by our Fedora affinity + docker's disregard for the cgroupv2 change (which is five years old or so)).

Avi, I was using the real docker and had to change to podman because you decided we all need to switch to Fedora 32 now, and docker which I had installed no longer worked... I didn't choose podman just to spite you, really 😂

**Comment by nyh** [comment]
> > 90% of the users encountering errors
> 
> Really, 90%? How come they're not flooding us with feedback about it?

I obviously made this number 90% up. I only know that everyone in *our* team I asked told me he had the same problem at some point. I guess Avi is right and most people don't actually use Fedora, so we at Scylla - Fedora diehards - are particularly susceptible to this problem more than the average user.

> 
> > if you don't bind-mount a storage volume (which is the proper way to run a database).
> 
> I suppose this might be common knowledge among certain professionals, but don't count on the average user knowing that. Does our getting-started guide mention that this is the only proper way? And if it does, how come @dorlaor , @nyh, and I managed to miss it?

I haven't seen or heard anything about this "storage volume" thing. I only use docker for temporary tests, I never cared enough to check what happens to the data if restarting the container. I just expected the container to run :-) I am guessing many users will do the same as me on their first run, and only later try to figure out how to enable additional data volumes.

**Comment by dekimir** [comment]
> If you don't bind-mound a storage volume, you'll lose all your data once the container is restarted.
> 
> It is [documented](https://docs.scylladb.com/operating-scylla/procedures/tips/best_practices_scylla_on_docker/#configuring-a-data-volume-for-storage) (but says nothing about the default storage being volatile)

Ah, sorry, I see that I misused the word "user".  What I meant by it is the reader of the getting-started guide, a person new to Scylla who just wants to give it a quick spin as they gain confidence and gradual understanding.  They'll get neither if bitten by this bug.  It's imperative for the getting-started procedure to work smoothly for the majority of such users.  They don't really care about data persistence at that stage, and they can't be relied on to guess the right Docker options beyond what the guide says.

**Comment by avikivity** [comment]
> > (and likely users are using the "real" docker, not podman, it's only Scylla developers who are driven to use podman by our Fedora affinity + docker's disregard for the cgroupv2 change (which is five years old or so)).
> 
> Avi, I was using the real docker and had to change to podman because you decided we all need to switch to Fedora 32 now, and docker which I had installed no longer worked... I didn't choose podman just to spite you, really

I know you didn't. And there is nothing wrong with using podman, it is better than docker IMO.

**Comment by avikivity** [comment]
> > If you don't bind-mound a storage volume, you'll lose all your data once the container is restarted.
> > It is [documented](https://docs.scylladb.com/operating-scylla/procedures/tips/best_practices_scylla_on_docker/#configuring-a-data-volume-for-storage) (but says nothing about the default storage being volatile)
> 
> Ah, sorry, I see that I misused the word "user". What I meant by it is the reader of the getting-started guide, a person new to Scylla who just wants to give it a quick spin as they gain confidence and gradual understanding. They'll get neither if bitten by this bug. It's imperative for the getting-started procedure to work smoothly for the majority of such users. They don't really care about data persistence at that stage, and they can't be relied on to guess the right Docker options beyond what the guide says.

That's true, but again ordinary users are unlikely to be using podman.
