### ISSUE TITLE
incorrect mount for scylla coredump 

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla#6300]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200426.`ac3c1f6c0fb`
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0eb50f8319265a36f`

```
Apr 27 16:13:37 longevity-lwt-500G-3d-lwt-data-db-node-bfcd94b7-2 systemd-coredump[96094]: Not enough disk space for coredump of 96060 (scylla), refusing.
Apr 27 16:13:38 longevity-lwt-500G-3d-lwt-data-db-node-bfcd94b7-2 systemd-coredump[96094]: Process 96060 (scylla) of user 996 dumped core.
Apr 27 16:13:38 longevity-lwt-500G-3d-lwt-data-db-node-bfcd94b7-2 systemd[1]: scylla-server.service: main process exited, code=dumped, status=6/ABRT
```

The bug is `var-lib-systemd-coredump.mount`
incorrect Mount definition causes the coredump  to be saved in `/var/lib/systemd/coredump`:
```
[Mount]
What=/var/lib/scylla/coredump
Where=/var/lib/systemd/coredump
Type=none
Options=bind
```
correct unit should be:
```
What=/var/lib/systemd/coredump
Where=/var/lib/scylla/coredump
```

**Comment by slivne** [comment]
Is this broken on 4.0 as well ?

**Comment by penberg** [comment]
@slivne The problem was introduced in https://github.com/scylladb/scylla/commit/5f18964763608b5e5d5a833c0777e253d2c21624, which is not in 4.0.

**Comment by syuu1228** [comment]
Maybe there is a bug on the setup script, but I think it's not a bug of var-lib-systemd-coredump.mount.
I tested it again now, just worked finely.
But I tested .mount file only, I don't say there is no bug on scylla_coredump_setup, will try to reproduce the issue now...

Here's the test of .mount file:
```
[centos@ip-10-0-0-60 coredump]$ cat /etc/systemd/system/var-lib-systemd-coredump.mount
[Unit]
Description=Save coredump to scylla data directory
Conflicts=umount.target
Before=scylla-server.service
After=local-fs.target

[Mount]
What=/var/lib/scylla/coredump
Where=/var/lib/systemd/coredump
Type=none
Options=bind

[Install]
WantedBy=multi-user.target
[centos@ip-10-0-0-60 ~]$ sudo systemctl start var-lib-systemd-coredump.mount
[centos@ip-10-0-0-60 ~]$ sudo systemctl status var-lib-systemd-coredump.mount
● var-lib-systemd-coredump.mount - Save coredump to scylla data directory
   Loaded: loaded (/etc/systemd/system/var-lib-systemd-coredump.mount; enabled; vendor preset: disabled)
   Active: active (mounted) since Tue 2020-04-28 07:26:44 UTC; 1s ago
    Where: /var/lib/systemd/coredump
     What: /dev/md0
  Process: 2597 ExecMount=/bin/mount /var/lib/scylla/coredump /var/lib/systemd/coredump -t none -o bind (code=exited, status=0/SUCCESS)

Apr 28 07:26:44 ip-10-0-0-60.ec2.internal systemd[1]: Mounting Save coredump to scylla data directory...
Apr 28 07:26:44 ip-10-0-0-60.ec2.internal systemd[1]: Mounted Save coredump to scylla data directory.
[centos@ip-10-0-0-60 coredump]$ mount|grep /var/lib/systemd
/dev/md0 on /var/lib/systemd/coredump type xfs (rw,noatime,seclabel,attr2,inode64,logbufs=8,logbsize=32k,sunit=2048,swidth=4096,noquota)
[centos@ip-10-0-0-60 coredump]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs         60G     0   60G   0% /dev
tmpfs            60G     0   60G   0% /dev/shm
tmpfs            60G   17M   60G   1% /run
tmpfs            60G     0   60G   0% /sys/fs/cgroup
/dev/xvda1       10G  5.8G  4.3G  58% /
tmpfs            12G     0   12G   0% /run/user/1000
/dev/md0        3.5T  102G  3.4T   3% /var/lib/scylla
[centos@ip-10-0-0-60 ~]$ cd /var/lib/systemd/coredump
[centos@ip-10-0-0-60 coredump]$ sudo dd if=/dev/zero of=./test bs=1G count=100
100+0 records in
100+0 records out
107374182400 bytes (107 GB) copied, 65.2373 s, 1.6 GB/s
```

**Comment by bentsi** [comment]
@syuu1228 
the issue is that you mount `/var/lib/scylla/coredump` into `/var/lib/systemd/coredump`. But you need to do the opposite.

Definition of `what` and `where`:
```
What=
Takes an absolute path of a device node, file or other resource to mount. See mount(8) for details. If this refers to a device node, a dependency on the respective device unit is automatically created. (See systemd.device(5) for more information.) This option is mandatory. Note that the usual specifier expansion is applied to this setting, literal percent characters should hence be written as "%%". If this mount is a bind mount and the specified path does not exist yet it is created as directory.

Where=
Takes an absolute path of a file or directory for the mount point; in particular, the destination cannot be a symbolic link. If the mount point does not exist at the time of mounting, it is created as directory. This string must be reflected in the unit filename. (See above.) This option is mandatory.
```
I opened PR that should fix this. https://github.com/scylladb/scylla/pull/6301

When testing that coredump created you also need to:

1. check that it is created in the correct path
2. remove the test coredump file after it was created

**Comment by slivne** [comment]
fixed by e77dad3adf7051a489223bbd55ecbc461b377421

**Comment by roydahan** [comment]
@bentsi / @syuu1228 seems like we still suffer from the issue.
see the issue that @ShlomiBalalis mentioned, we don't have the environment but if we can't get this from the logs we can try reproduce.

**Comment by bentsi** [comment]
@roydahan this is the same issue we encounter on OEL: #6402

**Comment by roydahan** [comment]
#6402 was opened specifically for OEL.
It seems like we still have issues with getting coredumps.
@amoskong is checking if it's this one / 6402 or a totally new one.

**Comment by amoskong** [comment]
I tried to started an instance with AMI ami-0eb50f8319265a36f in comment #0.
Scylla version (or git commit hash): 666.development-0.20200426.ac3c1f6c0fb

scylla-ami-setup service failed, but the scylla-server is running...
The status of var-lib-systemd-coredump.mount is inactive, scylla-ami-setup isn't executed as expected, so coredump setup isn't executed.

AS Bentsi said in https://github.com/scylladb/scylla/issues/6300#issuecomment-630280109, the problem (fail to generate coredump for enospc, mount isn't correct), the root caused is scylla-ami-setup config name issue, it's same as https://github.com/scylladb/scylla/issues/6402.

But currently in our 4.1 testing, the 6402 only occurred on OEL.

Current status in 4.1:
- issue #6042 doesn't exist on centos7 / AMI
- so scylla-ami-setup/coredump setup will be executed. but bentsi's fix is wrong, coredump setup will failed for `systemd[1]: var-lib-systemd-coredump.mount's Where= setting doesn't match unit name. Refusing.`. Finally the coredump can't be saved for enospc, /var/lib/systemd/coredump isn't mounted correctly.

WHAT WE NEED TODO:
- revert bentis's patch https://github.com/scylladb/scylla/commit/e77dad3adf7051a489223bbd55ecbc461b377421
- the original config is correct



```
Nodetool:
	nodetool help
CQL Shell:
	cqlsh
More documentation available at: 
	http://www.scylladb.com/doc/
By default, Scylla sends certain information about this node to a data collection server. For information, see http://www.scylladb.com/privacy/

Traceback (most recent call last):
  File "/opt/scylladb/scripts/scylla_util.py", line 617, in __init__
    run('systemctl {} cat {}'.format(self.ctlparam, unit), silent=True)
  File "/opt/scylladb/scripts/scylla_util.py", line 340, in run
    return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr, env=scylla_env)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['systemctl', 'cat', 'scylla-ami-setup.service']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scylladb/scylla-machine-image/libexec/scylla_login", line 115, in <module>
    setup = systemd_unit('scylla-ami-setup.service')
  File "/opt/scylladb/scripts/scylla_util.py", line 619, in __init__
    raise SystemdException('unit {} not found'.format(unit))
scylla_util.SystemdException: unit scylla-ami-setup.service not found
```
```
$ sudo systemctl status scylla-server
● scylla-server.service - Scylla Server
   Loaded: loaded (/usr/lib/systemd/system/scylla-server.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/scylla-server.service.d
           └─capabilities.conf, mounts.conf
   Active: active (running) since Tue 2020-06-02 06:41:17 UTC; 3min 9s ago
  Process: 1999 ExecStartPre=/opt/scylladb/scripts/scylla_prepare (code=exited, status=0/SUCCESS)
 Main PID: 2076 (scylla)
   Status: "serving"
   CGroup: /scylla.slice/scylla-server.slice/scylla-server.service
           └─2076 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml...

Jun 02 06:41:42 ip-10-99-0-64.ec2.internal scylla[2076]:  [shard 0] init - Launching generate_mv_updates for non system tables
Jun 02 06:41:42 ip-10-99-0-64.ec2.internal scylla[2076]:  [shard 0] init - starting the view builder
Jun 02 06:41:42 ip-10-99-0-64.ec2.internal scylla[2076]:  [shard 0] init - starting native transport
Jun 02 06:41:42 ip-10-99-0-64.ec2.internal scylla[2076]:  [shard 0] compaction - Compacting [/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628...evel=0, ]
Jun 02 06:41:42 ip-10-99-0-64.ec2.internal scylla[2076]:  [shard 0] storage_service - Starting listening for CQL clients on 0.0.0.0:9042 (unencrypted)
Jun 02 06:41:42 ip-10-99-0-64.ec2.internal scylla[2076]:  [shard 0] storage_service - Thrift server listening on 0.0.0.0:9160 ...
Jun 02 06:41:42 ip-10-99-0-64.ec2.internal scylla[2076]:  [shard 0] init - serving
Jun 02 06:41:42 ip-10-99-0-64.ec2.internal scylla[2076]:  [shard 0] init - Scylla version 666.development-0.20200426.ac3c1f6c0fb initialization completed.
Jun 02 06:41:42 ip-10-99-0-64.ec2.internal scylla[2076]:  [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system/truncated-38c19fd0fb863310a...ged to 2.
Jun 02 06:41:44 ip-10-99-0-64.ec2.internal scylla[2076]:  [shard 0] standard_role_manager - Created default superuser role 'cassandra'.
Hint: Some lines were ellipsized, use -l to show in full.
```

```
[centos@ip-10-99-0-64 ~]$ sudo systemctl status var-lib-systemd-coredump.mount
● var-lib-systemd-coredump.mount - Save coredump to scylla data directory
   Loaded: loaded (/etc/systemd/system/var-lib-systemd-coredump.mount; enabled; vendor preset: disabled)
   Active: inactive (dead)
    Where: /var/lib/systemd/coredump
     What: /var/lib/scylla/coredump
```

**Comment by amoskong** [comment]
Hi @roydahan 

The error "unit scylla-ami-setup.service not found" doesn't exist on latest scylla master and 4.1.
It caused the scylla-ami-setup failed, and coredump_setup won't be executed.
So `Not enough disk space` occurred after coredump is generating.

I think we can close this issue, because the root problem '"unit scylla-ami-setup.service not found"' doesn't exists now.

**Comment by roydahan** [comment]
@amoskong so it’s not clear if the issue is 6300 or something else?
If something else, please open such and move your comments there.

You are commenting on the existing issues and we can’t follow.

**Comment by amoskong** [comment]
> @amoskong so it’s not clear if the issue is 6300 or something else?
> If something else, please open such and move your comments there.

Just opened a new issue:
- var-lib-systemd-coredump.mount isn't started after setup #6566

> You are commenting on the existing issues and we can’t follow.
