### ISSUE TITLE
Materialized view replica updates use random timestamps

### ISSUE THREAD

**Issue by dekimir** [scylladb/scylla#6429]
There likely exists a race condition in MV replica updates; it stems from evaluating MV filters at timestamps not directly related to the underlying base operation.  I don't know how exactly it can be triggered or what its observable consequences may be; I am just reporting my source analysis here at @psarna's advice.

The method [`table::do_push_view_replica_updates()`](https://sourcegraph.com/github.com/scylladb/scylla@55d89d2cbe853b0d86d111f37c613a637efa4361/-/blob/table.cc?subtree=true#L2475) evaluates view matches with respect to a particular timestamp in order to ensure that MV's schema matches the write operation's base schema (an intent expressed in bfb8a3c172).  Unfortunately, the timestamp used is essentially random.  More unfortunately, multiple timestamps are mixed with each other.

Here is how it happens, according to my reading of the current source code:
- `table::do_push_view_replica_updates()` invokes `affected_views()` and `calculate_affected_clustering_ranges()`, which transitively invoke [`view::partition_key_matches()`](https://sourcegraph.com/github.com/scylladb/scylla@55d89d2cbe853b0d86d111f37c613a637efa4361/-/blob/db/view/view.cc?subtree=true#L172:6) and [`view::clustering_prefix_matches()`](https://sourcegraph.com/github.com/scylladb/scylla@55d89d2cbe853b0d86d111f37c613a637efa4361/-/blob/db/view/view.cc?subtree=true#L177); both of these functions evaluate the MV filter with timestamp=`gc_clock::now()`, which seems to have little relation to the underlying base operation's timestamp.
- later on, `table::do_push_view_replica_updates()` invokes `table::generate_and_propagate_view_updates()` and, transitively, [`db::view::generate_view_updates()`](https://sourcegraph.com/github.com/scylladb/scylla@55d89d2cbe853b0d86d111f37c613a637efa4361/-/blob/db/view/view.cc?subtree=true#L933:49); the latter creates a `view_update_builder` object, which captures `gc_clock::now()` as the relevant timestamp for evaluating the MV's filter; again, this seems unrelated to the underlying base operation's timestamp
  - the above timestamp (from `view_update_builder` construction time) is used for all view_updates thereby performed, by passing it down to [`view::matches_view_filter()`](https://sourcegraph.com/github.com/scylladb/scylla@55d89d2cbe853b0d86d111f37c613a637efa4361/-/blob/db/view/view.cc?subtree=true#L229:6); but `matches_view_filter()` mixes this timestamp with another `gc_clock::now()` when it invokes `view::clustering_prefix_matches()`

Note: names in blue above are links directly to the relevant source.

**Comment by psarna** [comment]
It looks like bfb8a3c was more about ensuring that we keep a schema version corresponding to the update, in case somebody updates the schema in the middle of view update generation. The original source of allowing reads with a timestamp is here: 7be0f319d4 , and I think that it's not as much about using user-provided timestamps as I previously thought, but simply as a way of checking if the cells we read are alive or dead. If that was indeed the intention, then the potential races are probably benign, e.g. `affected_views()` returns a view, because one of the rows was still alive, but then the rows die right before `calculate_affected_clustering_ranges()` is called - and nothing of value is lost really, since the rows are dead and they should not produce any view updates.

So, my hypothesis is that while the infrastructure provided in 7be0f319d4 is actually useful and could also be used to check the restrictions for user-provided timestamps, the root cause of having multiple `gc_clock::now()`s passed is simply that the interface required passing a time point, so the author put the most obvious time point here - the current one, in order to avoid adding a time_point parameter all over the call hierarchy. It's probably more correct to indeed add this parameter everywhere, but on the other hand I don't see any actual inconsistencies that may be caused by using different time points as we do now (different, but still monotonic). Does anyone have an idea what could go wrong?

**Comment by dekimir** [comment]
>
> a way of checking if the cells we read are alive or dead
>

But then why doesn't regular filtering perform the same check? How are dead
cells different from live ones in the fetched data?

**Comment by psarna** [comment]
Huh, you got me scared really bad that we wrongly assume that all cells are live and try to take their value if they're dead... fortunately, filtering is only applied to live columns, since the cells come from this class:
```cpp
query-result-reader.hh:
// Contains cells in the same order as requested by partition_slice.
// Contains only live cells.
class result_row_view {
```
So, in short, what we get from filtering is already preprocessed, and all dead cells are gone from it, hence there's no need to check if they're alive. The stuff we filter during "view filtering" is different, because it operates on raw data read from mutation readers, which can contain tombstones and expired cells. This process is called "view filtering", but it actually doesn't have much in common (in terms of implementation) with *the* filtering that we use in CQL via ALLOW FILTERING keywords.

**Comment by dekimir** [comment]
> This process is called "view filtering", but it actually doesn't have much in common (in terms of implementation) with the filtering that we use in CQL via ALLOW FILTERING keywords.

That's surprising, as I'd expect to see consistent behaviour between the two and identical restriction-evaluation code apart from `do_get_value()`.

Aside from that, I still don't understand why it's OK to use multiple different `now()`s.  Surely there must be some scenario where that yields surprising results?  If not, why do we even pass the timestamp down the call chain?  Why don't we just use `now()` in `restriction::is_satisfied_by()`?

**Comment by psarna** [comment]
That I don't know, but I suspect that author's vision was to eventually add these time points to the whole call chain, and simply use `now()`s as stubs until that's done. Current behavior is pretty much equivalent to just using now() inside is_satisfied_by() in terms of safety, so we can just do that and make the interfaces simpler.

And yet... I can't think of any scenario that yields inconsistencies, but I wouldn't be surprised if there was one... I'll try to figure something out tomorrow. If anyone comes up with a scenario where this issue results in an inconsistency, then we should fix it with high priority and backports.

**Comment by slivne** [comment]
If I understand the issue correctly

We may generate a tombstone on one base-view pair and not generate it on another base-view pair. Since each base will query the current data with a bit different now() so one can return data from the base table and another will not (in case the base table data has a TTL attached to it). 

Table tb {
   x int,
   y int,
   v int.
   primary key (x)
}
create materialized view tbv on tb (y,x)


insert tb (x,y,v) values (1,1,1) using ttl 20;


Node A x=1,y=1,v=1 (ttl=20) --> tbv y=1,x=1,v=1)(ttl=20)
Node B x=1,y=1,v=1 (ttl=20)  --> tbv y=1,x=1,v=1)(ttl=20)

t=~19 update tb set y=8,v=1 where x=1 using ttl 40;
Node A  (t=19) x=1,y=8,v=1 (ttl=40), tbv tombstone y=1,x=1 (time=19), y=8,x=1,v=1 (ttl=40)
Node B (t=21) x=1,y=8,v=1 (ttl=40), tbv tombstone y=1,x=1 (time=20), y=8,x=1,v=1 (ttl=40)

Its not a correctness issue but it will cause repair later to find difference between the two views - although all had all the updates and started from the same state.

So we should use one timestamp when reading the base table on all replicas.

**Comment by avikivity** [comment]
@psarna @nyh please evaluate for backport

**Comment by nyh** [comment]
I don't know how to decide. This patch did not solve any known bug, it has no unit test, and none of us every came up with a scenario where the old code was wrong. It just looked (IIRC) that the new code is "more correct". So perhaps we shouldn't backport... @psarna do you think we should?

**Comment by psarna** [comment]
No, I think it's not a backport candidate, especially that we never even saw any failure fixed by this patch. It just makes the code more future-proof.
