### ISSUE TITLE
A long scan which filters out most rows can return incomplete results

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7966]
In the following cql-pytest test, we have a `SELECT` request which scans an entire table and filters out, with `ALLOW FILTERING`, all the rows except one. This is a difficult case for Scylla, because the scan either needs to return empty pages which are problematic (it's unclear whether the protocol or drivers allow them) or risk timing out the request. But we never want to see what the test below shows: an **empty** result at the end of the scan, instead of the one expected result.

```python
from util import new_test_table
import pytest
def test_filtering_with_few_matches(cql, test_keyspace):
    count = 40000
    with new_test_table(cql, test_keyspace,
            "p int, c int, v int, PRIMARY KEY (p, c)") as table:
        stmt = cql.prepare(f"INSERT INTO {table} (p, c, v) VALUES (?, ?, ?)")
        for i in range(count):
            cql.execute(stmt, [i, i*10, i*100])
        assert list(cql.execute(f"SELECT p FROM {table} WHERE v=100 ALLOW FILTERING")) == [(1,)]
```

The same test passes on Cassandra.

My first guess was that Scylla either returned an empty page which misled the driver into stopping the iteration (I used Python's cassandra-driver 3.23.0), or, Scylla itself stopped the scan for some unknown reason. We need to debug which of these is the right explanation and how we can avoid it.

However it is important to note that I can only reproduce this bug in a full-table scan. When I try almost the same thing except all the rows are in a single partition, the test below works and we don't lose the results. This may make some of the explanations above (like an empty page) unlikely, because the same problem would have occured in the single-partition scan as well.

```python
def test_filtering_single_partition_with_few_matches(cql, test_keyspace):
    count = 400000
    with new_test_table(cql, test_keyspace,
            "p int, c int, v int, PRIMARY KEY (p, c)") as table:
        stmt = cql.prepare(f"INSERT INTO {table} (p, c, v) VALUES (?, ?, ?)")
        for i in range(count):
            cql.execute(stmt, [1, i*10, i*100])
        assert list(cql.execute(f"SELECT c FROM {table} WHERE p=1 AND v=100 ALLOW FILTERING")) == [(10,)]
```

UPDATE: this second test obviously doesn't miss the matching item because it is the first one... But even if we change the condition from v=100 to v=(count-1)*100, the second test passes.

I marked this issue as having "low" priority because workloads which rely on very selective filtering - reading an entire table only to return a very small number of results - are inherently inefficient and therefore unlikely. Nevertheless, this is a bug, that users may expose in rare but important (for them) cases, and should be fixed.

**Comment by slivne** [comment]
@nyh we just fixed https://github.com/scylladb/scylla/issues/8162 - which can be the root cause of this - can you please validate. 

A query not returning correct results can't be overlooked - so if its not that - we will need to find the source and fix it.

**Comment by nyh** [comment]
Unfortunately, although the problem that @denesb found in #8162 is probably related to the cause of this issue, it is not the same. It affects paged queries, not unpaged, and doesn't happen when we pass 100 MB - it happens when we pass just 1 MB (I guess some default page size maximum).  The test I wrote for this issue still fails on master with that issue's fix.

I wrote a new version of the test with a much more reasonable runtime (just 0.4 seconds, instead of of 30 seconds for the test above), and will send an xfailing test to the mailing list now.

**Comment by nyh** [comment]
I just sent a patch to the mailing list with a new cql-pytest:

* `test_filtering.py`::`test_filtering_with_few_matches`

This test reproduces this issue in less than a second.

@denesb it would be great if you can take a look at it - the underlying cause is probably similar to those other bugs you fixed recently.

**Comment by denesb** [comment]
@nyh I don't think the problem is with the range scan itself, just reading all data back is successfull:
```diff
diff --git a/test/cql-pytest/test_filtering.py b/test/cql-pytest/test_filtering.py
index ace00fb16..5d64ea406 100644
--- a/test/cql-pytest/test_filtering.py
+++ b/test/cql-pytest/test_filtering.py
@@ -60,15 +60,22 @@ def test_filter_on_unset(cql, test_keyspace):
 #    to find a partition near the end of the scan, and use that in the filter.
 # Both tricks allowed us to reduce "count" below from 40,000 in the original
 # reproducer of #7966 to just 100, and the test's time from 30 seconds to 0.4.
-@pytest.mark.xfail(reason="issue #7966")
+#@pytest.mark.xfail(reason="issue #7966")
 def test_filtering_with_few_matches(cql, test_keyspace):
     count = 100
     long='x'*60000
     with new_test_table(cql, test_keyspace,
             "p int, c text, v int, PRIMARY KEY (p, c)") as table:
         stmt = cql.prepare(f"INSERT INTO {table} (p, c, v) VALUES (?, '{long}', ?)")
+        expected_data = list()
         for i in range(count):
+            expected_data.append((i, long, i*100))
             cql.execute(stmt, [i, i*100])
+
+        res = list(cql.execute(f"SELECT * FROM {table}"))
+        res.sort(key=lambda x: x[0])
+        assert res == expected_data
+
         p, v = list(cql.execute(f"SELECT p, v FROM {table} WHERE TOKEN(p) > 8000000000000000000 LIMIT 1"))[0]
         assert list(cql.execute(f"SELECT p FROM {table} WHERE v={v} ALLOW FILTERING")) == [(p,)]
```
The filtering does a similar page scan behind the scenes.

**Comment by nyh** [comment]
Hi @denesb,
One of the guesses I made in the original bug description was that the paging stopped after a hard limit (1 MB?) and the filtering left zero rows, which perhaps confused the driver. If this was the case then it would indeed be very different from #8162. 

HOWEVER, this guess doesn't explain how come exactly the same test works when scanning a single partition instead of the whole table (partition-range scan) - I included that test in the patch as well (with "skip" mark). This is why I though Shlomi might have been correct that this is also an issue with how partition-range scans work differently from single-partition scans.

**Comment by denesb** [comment]
Interestingly, I cannot reproduce if I make the value large, instead of the clustering key. The bug may be in the handling of such a large clustering key.

**Comment by denesb** [comment]
Actually the problem seems to be related to the column kind we filter on. If I filter on a clustering column, it works, if I filter on a regular one, it doesn't.

**Comment by nyh** [comment]
@denesb
1. Large clustering key is not the problem - my original example (on the top of this issue) included small clustering keys. I used large ones just to make this test much faster.
2. Yes, "filtering" needs to happen on a non-clustering key - if the condition is on a clustering key, filtering is not needed - the read can find the right place immediately.

**Comment by denesb** [comment]
> @denesb
> 
>     1. Large clustering key is not the problem - my original example (on the top of this issue) included small clustering keys. I used large ones just to make this test much faster.

Right, I didn't see that.

> 
>     2. Yes, "filtering" needs to happen on a non-clustering key - if the condition is on a clustering key, filtering is not needed - the read can find the right place immediately.

Right, I forgot, yes of course, if we have a clustering restriction, it is just included in the slice, no filtering is needed.

**Comment by denesb** [comment]
It looks like the pager is simply not invoked to fetch the next page, after returning the 2nd one. I think the problem might be in the driver, the pager is not-exhausted so we do set a paging state in the (empty) page returned to driver.

**Comment by denesb** [comment]
I captured the trafic with Wireshark and indeed there are two pages sent to the client, and the last page has `has_more_pages=true`, but the driver doesn't request any more pages.
One strange thing I saw though that the paging state seems to contain the huge value we use, even though in my case it is just a regular column. I want to have a closer look at why this happens.

**Comment by denesb** [comment]
@nyh what was the context in which you originally saw this issue? Which driver? I think we'll need someone who understands how the driver works.

**Comment by denesb** [comment]
> One strange thing I saw though that the paging state seems to contain the huge value we use, even though in my case it is just a regular column. I want to have a closer look at why this happens.

The paging state looks sane in scylla, printed it both before sending it to the client and on the start of the page.

**Comment by nyh** [comment]
> @nyh what was the context in which you originally saw this issue? Which driver? I think we'll need someone who understands how the driver works.

I don't remember why I wrote this test (the original slow version with a gazillion rows), I think I was testing some bugs related to scanning through a huge number of _deleted_ rows, and then I wondered what would happen if I didn't delete them, just filter them out.

As all the `cql-pytest` tests, this test is using the Cassandra Python driver. Looking at my Python library directory, I see I am using version of 3.23.0 from Datastax. I don't know if this specific version is needed to reproduce this bug - IIUC you also were able to reproduce it in whatever version of the driver you have. In any case, this is an issue discovered by my test - it was not (as far as I know...) reported by a user.

You're right that it's possible that it's a driver bug - e.g., that the driver fails to request more pages despite have_more_pages. In the past, I remember we had long arguments whether empty pages (with have_more_pages) are supported in drivers, but I don't remember what the conclusion was. 

However, I am still curious, if this is a bug in the driver, how could this bug be specific to whole-table scan and now happen in a single-partition scan. There has to be some difference between the two implementations. Could it be that our full-table scan implementation stops a page after scanning 1MB, but our single-partition scan does NOT stop until returning (not just scanning...) enough results?

**Comment by denesb** [comment]
Indeed Scylla is sending empty pages to the driver, both pages sent to the driver are empty, however the driver only stops after the second one. Even if the driver has a problem with empty pages, it only has a problem with certain empty pages -- as it happily requests a new page after the first empty one.

**Comment by denesb** [comment]
I just checked and in the case of the single partition query, the first page already contains the sough-after row, so there are no empty pages.

**Comment by nyh** [comment]
> I just checked and in the case of the single partition query, the first page already contains the sough-after row, so there are no empty pages.

Which test was this? The original test on this issue? I found a bug in it and wrote an "UPDATE" above. The test I sent in a patch did not have that bug. If that non-buggy test returned a non-empty page it means (I think) that the paged scan in the single-partition case did not stop after 1MB, whereas the paged scan in the multi-partition scan did stop after 1MB. I don't know which is worse. Not stopping is also bad, because it means we can have unbounded latency.

**Comment by denesb** [comment]
> > I just checked and in the case of the single partition query, the first page already contains the sough-after row, so there are no empty pages.
> 
> Which test was this? The original test on this issue? I found a bug in it and wrote an "UPDATE" above. The test I sent in a patch did not have that bug. If that non-buggy test returned a non-empty page it means (I think) that the paged scan in the single-partition case did not stop after 1MB, whereas the paged scan in the multi-partition scan did stop after 1MB. I don't know which is worse. Not stopping is also bad, because it means we can have unbounded latency.

I checked the test from the patch you sent to the list, the one marked with `@pytest.mark.skip`.

**Comment by denesb** [comment]
I tweaked said test to not have the sough-after row on the first page and hence send empty pages to the driver and now that test fails too.

**Comment by denesb** [comment]
@nyh I think you should rename this issue to something more relevant to the issue we traced this back to: the python driver (and maybe others too) seems to give up on filtering queries after the second empty page, even if `has_more_pages=true`. The kind of query (range scan or single partition scan) doesn't seem to make a difference.

**Comment by nyh** [comment]
> I tweaked said test to not have the sough-after row on the first page and hence send empty pages to the driver and now that test fails too.

Hmm, the single-partition test only matched the *last* item, so it shouldn't have the sought-after row on the first page... What am I missing? What is your tweak?

**Comment by slivne** [comment]
Thee is an old thread "Python Driver and Empty Pages" - I think it may be
related to this

**Comment by denesb** [comment]
> > I tweaked said test to not have the sough-after row on the first page and hence send empty pages to the driver and now that test fails too.
> 
> Hmm, the single-partition test only matched the _last_ item, so it shouldn't have the sought-after row on the first page... What am I missing? What is your tweak?

My tweak was very simple:
```diff
@@ -86,4 +99,4 @@ def test_filtering_single_partition_with_few_matches(cql, test_keyspace):
         stmt = cql.prepare(f"INSERT INTO {table} (p, c, v, s) VALUES (1, ?, ?, '{long}')")
         for i in range(count):
             cql.execute(stmt, [i, i])
-        assert list(cql.execute(f"SELECT c FROM {table} WHERE p=1 AND v={count-1} ALLOW FILTERING")) == [(count-1,)]
+        assert list(cql.execute(f"SELECT c, s FROM {table} WHERE p=1 AND v={count-1} ALLOW FILTERING")) == [(count-1,)]
```
Include the heavy `s` column to make rows larger and therefore get the page cut before getting to the row of interest.
I think the reason why we did get almost all rows in a single page in this test but not in the range-scan one, is that the latter one has a lot of partitions taking up space in the result, so the page gets cut sooner (with less rows).

**Comment by nyh** [comment]
> > > I tweaked said test to not have the sough-after row on the first page and hence send empty pages to the driver and now that test fails too.
> > 
> > 
> > Hmm, the single-partition test only matched the _last_ item, so it shouldn't have the sought-after row on the first page... What am I missing? What is your tweak?
> 
> My tweak was very simple:
> 
> ```diff
> @@ -86,4 +99,4 @@ def test_filtering_single_partition_with_few_matches(cql, test_keyspace):
>          stmt = cql.prepare(f"INSERT INTO {table} (p, c, v, s) VALUES (1, ?, ?, '{long}')")
>          for i in range(count):
>              cql.execute(stmt, [i, i])
> -        assert list(cql.execute(f"SELECT c FROM {table} WHERE p=1 AND v={count-1} ALLOW FILTERING")) == [(count-1,)]
> +        assert list(cql.execute(f"SELECT c, s FROM {table} WHERE p=1 AND v={count-1} ALLOW FILTERING")) == [(count-1,)]
> ```
> 
> Include the heavy `s` column to make rows larger and therefore get the page cut before getting to the row of interest.

Interesting! So I guess it goes back, again, to the fact that one type of scan collects the entire results not just the columns of interest, and the other collects only the column of interest. Which may also be a performance waste which maybe needs to be addressed (I think you already did?), but not *this* bug.

So I guess I should close this issue and open a new one with a clearer understanding of the problem: that the Python driver (we still don't know if other drivers also have this problem) stop paging prematurely after two (?) empty pages - and it happens for any scan (single partition scan or whole table scan).

**Comment by denesb** [comment]
On Tue, Mar 2, 2021, 17:28 nyh <notifications@github.com> wrote:

> I tweaked said test to not have the sough-after row on the first page and
> hence send empty pages to the driver and now that test fails too.
>
> Hmm, the single-partition test only matched the *last* item, so it
> shouldn't have the sought-after row on the first page... What am I missing?
> What is your tweak?
>
> My tweak was very simple:
>
> @@ -86,4 +99,4 @@ def test_filtering_single_partition_with_few_matches(cql, test_keyspace):
>          stmt = cql.prepare(f"INSERT INTO {table} (p, c, v, s) VALUES (1, ?, ?, '{long}')")
>          for i in range(count):
>              cql.execute(stmt, [i, i])-        assert list(cql.execute(f"SELECT c FROM {table} WHERE p=1 AND v={count-1} ALLOW FILTERING")) == [(count-1,)]+        assert list(cql.execute(f"SELECT c, s FROM {table} WHERE p=1 AND v={count-1} ALLOW FILTERING")) == [(count-1,)]
>
> Include the heavy s column to make rows larger and therefore get the page
> cut before getting to the row of interest.
>
> Interesting! So I guess it goes back, again, to the fact that one type of
> scan collects the entire results not just the columns of interest, and the
> other collects only the column of interest. Which may also be a performance
> waste which maybe needs to be addressed (I think you already did?), but not
> *this* bug.
>
This problem doesn't play a part in what we see here. In faxt one of the
first things I tried was to run this against my efficiency fix for range
scan result building, and I got the same result. The difference is simply
due to eay data is organized in these tests. The multi partition test has
many partitions with a single row, while the single partition test has a
single partition with many rows.

So I guess I should close this issue and open a new one with a clearer
> understanding of the problem: that the Python driver (we still don't know
> if other drivers also have this problem) stop paging prematurely after two
> (?) empty pages - and it happens for any scan (single partition scan or
> whole table scan).
>

Yes, either rename this issue or close it and open a new one. I'm fairly
confident that the problem is not on the scylla side, and most certainly
not on the replica side.

**Comment by denesb** [comment]
On Tue, Mar 2, 2021, 18:07 Botond Dénes <bdenes@scylladb.com> wrote:

>
>
> On Tue, Mar 2, 2021, 17:28 nyh <notifications@github.com> wrote:
>
>> I tweaked said test to not have the sough-after row on the first page and
>> hence send empty pages to the driver and now that test fails too.
>>
>> Hmm, the single-partition test only matched the *last* item, so it
>> shouldn't have the sought-after row on the first page... What am I missing?
>> What is your tweak?
>>
>> My tweak was very simple:
>>
>> @@ -86,4 +99,4 @@ def test_filtering_single_partition_with_few_matches(cql, test_keyspace):
>>          stmt = cql.prepare(f"INSERT INTO {table} (p, c, v, s) VALUES (1, ?, ?, '{long}')")
>>          for i in range(count):
>>              cql.execute(stmt, [i, i])-        assert list(cql.execute(f"SELECT c FROM {table} WHERE p=1 AND v={count-1} ALLOW FILTERING")) == [(count-1,)]+        assert list(cql.execute(f"SELECT c, s FROM {table} WHERE p=1 AND v={count-1} ALLOW FILTERING")) == [(count-1,)]
>>
>> Include the heavy s column to make rows larger and therefore get the
>> page cut before getting to the row of interest.
>>
>> Interesting! So I guess it goes back, again, to the fact that one type of
>> scan collects the entire results not just the columns of interest, and the
>> other collects only the column of interest. Which may also be a performance
>> waste which maybe needs to be addressed (I think you already did?), but not
>> *this* bug.
>>
> This problem doesn't play a part in what we see here. In faxt one of the
> first things I tried was to run this against my efficiency fix for range
> scan result building, and I got the same result. The difference is simply
> due to eay data is organized in these tests. The multi partition test has
> many partitions with a single row, while the single partition test has a
> single partition with many rows.
>


It actually may be at play but it doesn't influence the result of the test
one way or another.

**Comment by nyh** [comment]
Closing this issue, and I will open a new one and send a patch to the tests now that we better (although not yet fully) understand this issue.
