### ISSUE TITLE
"Cannot achieve consistency level for cl ONE. Requires 1, alive 0" while just one node is down

### ISSUE THREAD

**Issue by gibsn** [scylladb/scylla#8498]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [*] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.1.10-0.20201201.9ea2a61d6
Cluster size: 9
OS (RHEL/CentOS/Ubuntu/AWS AMI): C7.5

*Hardware details (for performance issues)* 
Platform (physical/VM/cloud instance type/docker): bare metal
Hardware: sockets=2 cores=2 hyperthreading=yes memory=128gb
Disks: (SSD/HDD, count) 1TB RAID 1 SSD for commitlogs, 10 HDDs 16TB RAID 10 for data

Hi!

We have a cluster of 2 DCs, 4 nodes in the first one, 5 nodes in the second one, RF=1 inside each DC. We started getting lots of "Cannot achieve consistency level for cl ONE. Requires 1, alive 0" errors when we stopped just one node, errors disappeared only when we started that node. Here is what we did:
1. Started replacing node 10.161.180.24
2. Replace failed because another node became unresponsive for some limited period of time
3. We stopped 10.161.180.24 in order to restart replace
4. We started getting lots of "Cannot achieve consistency level for cl ONE. Requires 1, alive 0" write errors. We do both writes and reads with CL=ONE, however writes failed and reads succeeded 
5. We restarted 10.161.180.24, started replace and everything went back to normal

`nodetool status` during the problem:
```
Datacenter: DC1
==============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens       Owns    Host ID                               Rack
UN  10.161.192.33  22.88 TB   256          ?       8150d696-01bf-4dfe-8d45-cf5dc7fa2795  RACK3
DN  10.161.180.24  10.5 TB    256          ?       293f1897-9507-4254-953c-57b10d5ebe16  RACK1
UN  10.161.245.10  25.24 TB   256          ?       7fc5e8d1-a1d2-49a1-b006-9aafbfa0b392  RACK4
UN  10.161.179.28  11.12 TB   256          ?       62a49e18-9272-4e83-a822-a50f4213d22a  RACK2
Datacenter: DC2
==============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens       Owns    Host ID                               Rack
UN  10.161.175.35  11.72 TB   256          ?       de1f12d2-5ef0-459a-880e-7ed4ad22aae5  RACK2
UN  10.161.19.118  20.69 TB   256          ?       2b93f3f8-5a4b-4a14-b9ac-e61fd7440487  RACK5
UN  10.161.149.12  19.89 TB   256          ?       be62519c-b340-4da1-86c5-daaa343a10b0  RACK3
UN  10.161.173.28  10.91 TB   256          ?       82c9a93e-4793-409d-8305-388474b2496c  RACK1
UN  10.161.236.46  19.07 TB   256          ?       d9746386-69b3-4e3a-9c51-c1b4adc6ceeb  RACK4
```

Why cluster became unavailable for CL=ONE writes with one node down?

**Comment by gibsn** [comment]
We tried restarting replace again and faced the same situation. Looks like issue is easily reproducible in our production cluster

**Comment by tzach** [comment]
Do you have application access to both DC?
If not, a node down and RF=1 means the data is not available 

Please share the logs of the problematic node.

**Comment by gibsn** [comment]
> Do you have application access to both DC?

Yes, otherwise reads would have failed as well, I guess

**Comment by gibsn** [comment]
beccasc1 -- the problematic node
beccasc3 -- a node from a different DC

FYI I removed the "large_data" logs because those contain user data

[beccasc1.log](https://github.com/scylladb/scylla/files/6335774/beccasc1.log)
[beccasc3.log](https://github.com/scylladb/scylla/files/6335778/beccasc3.log)

**Comment by slivne** [comment]
@bhalevy please have someone help @gibsn out -  he is also available on slack.

**Comment by slivne** [comment]
(to make it clear lets help him replace the node), the error he got should be chased after that is done.

**Comment by bhalevy** [comment]
@asias can you please help on this issue?

**Comment by asias** [comment]
```

   1 Started replacing node 10.161.180.24
   2 Replace failed because another node became unresponsive for some limited period of time
   3 We stopped 10.161.180.24 in order to restart replace
   4 We started getting lots of "Cannot achieve consistency level for cl ONE. Requires 1, alive 0" write errors. We do both writes and reads with CL=ONE, however writes failed and reads succeeded
   5 We restarted 10.161.180.24, started replace and everything went back to normal
```

The problem is that after step 3, replacing does not revert the cluster back to the state before replacing. Other nodes in the cluster still think the replacing node 10.161.180.24 is doing replace and sends the writes to the replacing node as pending ranges. 

This problem is solved in master commit 323f72e48a7d89d9edc40257a1f45c202accc146 (repair: Switch to use NODE_OPS_CMD for replace operation) .

I saw your cluster uses HDD. You can try:

Set 

compaction_enforce_min_threshold = true

compaction_static_shares = 200

To make the compaction less aggressive to have a better chance to make the replace success.

**Comment by gibsn** [comment]
@asias thank you for response

> The problem is that after step 3, replacing does not revert the cluster back to the state before replacing. Other nodes in the cluster still think the replacing node 10.161.180.24 is doing replace and sends the writes to the replacing node as pending ranges.

I don't understand how it leads to the problem that we see. So after step 3 dead 10.161.180.24 is considered replacing by mistake, writes to that node from other nodes fail, but we still have another node for the same ranges which is alive and can serve CL=ONE writes well, however we get errors. Why CL=ONE writes fail if we have enough alive nodes?

**Comment by gibsn** [comment]
> Set

compaction_enforce_min_threshold = true

compaction_static_shares = 200

To make the compaction less aggressive to have a better chance to make the replace success.

We restarted the replace with this arguments as you suggested when we talked on Slack, thank you. We 10 static shares per shard so the total for the node is 300 now

**Comment by asias** [comment]
Good to hear. I am closing this issue since we have a fix in the master. @glbsn thanks for reporting.
